<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Articulos] (ficha completa estilo legacy).
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'descripcion' => 'Descripcion',
    'alternativo' => 'Alternativo',
    'codigoB2B' => 'CodigoB2B',
    'idWeb' => 'idWeb',
    'familia' => 'Familia',
    'subfamilia' => 'Subfamilia',
    'seccion' => 'Seccion',
    'subSeccion' => 'SubSeccion',
    'agrupacion' => 'Agrupacion',
    'proveedorHabitual' => 'UltProveedor',
    'impuestoCodigo' => 'Impuesto',
    'impuestoAgrario' => 'CodIvaAgrario',
    'precioVenta' => 'PrecioVen1',
    'precioVen1' => 'PrecioVen1',
    'precioVen2' => 'PrecioVen2',
    'precioVen3' => 'PrecioVen3',
    'precioVen4' => 'PrecioVen4',
    'precioVen5' => 'PrecioVen5',
    'precioVen6' => 'PrecioVen6',
    'precioVen7' => 'PrecioVen7',
    'precioVen8' => 'PrecioVen8',
    'precioVen9' => 'PrecioVen9',
    'precioBase' => 'PrecioBaseUltimo',
    'precioUltimo' => 'PrecioUltimo',
    'precioUltimoST' => 'PrecioUltimoST',
    'precioMedio' => 'PrecioMedio',
    'precioMedioST' => 'PrecioMedioST',
    'porcentajeCosteSobreVenta' => 'PorcentajeCosteSobreVenta',
    'cantidad1' => 'Cantidad1',
    'precioEsp1' => 'PrecioEsp1',
    'cantidad2' => 'Cantidad2',
    'precioEsp2' => 'PrecioEsp2',
    'cantidad3' => 'Cantidad3',
    'precioEsp3' => 'PrecioEsp3',
    'cantidad4' => 'Cantidad4',
    'precioEsp4' => 'PrecioEsp4',
    'cantidad5' => 'Cantidad5',
    'precioEsp5' => 'PrecioEsp5',
    'cantidad6' => 'Cantidad6',
    'precioEsp6' => 'PrecioEsp6',
    'cantidad7' => 'Cantidad7',
    'precioEsp7' => 'PrecioEsp7',
    'cantidad8' => 'Cantidad8',
    'precioEsp8' => 'PrecioEsp8',
    'pesoKilogramos' => 'PesoEnKilos',
    'volumen' => 'Volumen',
    'transporteEspecial' => 'TransporteEspecial',
    'empaquetado' => 'Empaquetado',
    'unidadEmpaquetado' => 'UnidadEmpaquetado',
    'unidadesCompra' => 'UnidadesCompra',
    'unidadStock' => 'UnidadStock',
    'envioWeb' => 'EnvioWeb',
    'tiendaWeb' => 'tiendaWeb',
    'bloqueoCompra' => 'BloqueoCompra',
    'bloqueoVenta' => 'BloqueoVenta',
    'bloqueoFidelizacion' => 'BloqueoFidelizacion',
    'servicio' => 'Servicio',
    'ventaPorPeso' => 'VentaPorPeso',
    'pasaporteFitosanitario' => 'PasaporteFitosanitario',
    'lotePasaporte' => 'LotePasaporte',
    'fitoProfesional' => 'FitoProfesional',
    'registroSanitario' => 'RegistroSanitario',
    'codigoIntrastat' => 'CodigoIntrastat',
    'estado' => 'Estado',
    'inventario' => 'Inventario',
    'ventaSoloReserva' => 'VentaSoloReserva',
    'etiquetaPrecio' => 'EtiquetaPrecio',
    'retIrpf' => 'RetIrpf',
    'impresionFichaBotanica' => 'ImpresionFichaBotanica',
    'etiquetaElectronica' => 'EtiquetaElectronica',
    'solicitarLote' => 'SolicitarLote',
    'fechaUltCompra' => 'FechaUltComp',
    'fechaAlta' => 'FechaAlta',
    'fechaBaja' => 'FechaBaja',
    'categoria' => 'Categoria',
    'contramarca' => 'Contramarca',
    'nombreBotanico' => 'NombreBotanico',
    'floracion' => 'Floracion',
    'altura' => 'Altura',
    'exposicion' => 'Exposicion',
    'poda' => 'Poda',
    'tipoPlanta' => 'TipoPlanta',
    'numAlveolos' => 'NumAlveols',
    'udsXAlveolo' => 'UdsXAlveol',
    'udsXSobre' => 'UdsXSobre',
    'stockBandejas' => 'StockBandejas',
    'literalPlanta1' => 'LiteralPlanta1',
    'literalPlanta2' => 'LiteralPlanta2',
    'patron' => 'Patron',
    'variedad' => 'Variedad',
    'comentarios' => 'Comentarios',
    'observaciones' => 'Observaciones',
    'observacionesComerciales' => 'ObservacionesVenta',
    'pendienteRecibir' => 'PendienteRecibir',
    'pendienteEntrega' => 'PendienteEntrega',
    'activo' => 'FechaBaja',
  ],
  'booleanFields' => [
    'transporteEspecial', 'envioWeb', 'bloqueoCompra', 'bloqueoVenta', 'bloqueoFidelizacion',
    'servicio', 'ventaPorPeso', 'pasaporteFitosanitario', 'lotePasaporte', 'fitoProfesional',
    'ventaSoloReserva', 'etiquetaPrecio', 'retIrpf', 'impresionFichaBotanica',
    'etiquetaElectronica', 'solicitarLote', 'stockBandejas', 'activo',
  ],
];
