<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Clientes] (ficha completa estilo legacy).
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'fechaAlta' => 'FechaAlta',
    'activo' => 'Baja',
    'nombre' => 'RazonSocial',
    'razonSocial2' => 'RazonSocial2',
    'actividad' => 'Actividad',
    'nif' => 'NIF',
    'personaContacto' => 'PersonaContacto',
    'direccion' => 'Direccion',
    'poblacion' => 'Poblacion',
    'provincia' => 'Provincia',
    'pais' => 'Pais',
    'codigoPostal' => 'CodigoPostal',
    'telefono1' => 'Telefono1',
    'telefono2' => 'Telefono2',
    'fax' => 'Fax',
    'direccionEnvio' => 'DireccionEnvio',
    'poblacionEnvio' => 'PoblacionEnvio',
    'codigoPostalEnvio' => 'CodigoPostalEnvio',
    'provinciaEnvio' => 'ProvinciaEnvio',
    'paisEnvio' => 'PaisEnvio',
    'email' => 'Email',
    'emailComercial' => 'EmailComercial',
    'emailFacturacion' => 'EmailFacturacion',
    'dto1' => 'Dto1',
    'dto2' => 'Dto2',
    'dto3' => 'Dto3',
    'escalado' => 'Escalado',
    'swIva' => 'SW_IVA',
    'swRec' => 'SW_Rec',
    'vendedor' => 'Vendedor',
    'agenteOrigen' => 'AgenteOrigen',
    'formaPago' => 'FormaPago',
    'diaPago1' => 'DiaPago1',
    'diaPago2' => 'DiaPago2',
    'agencia' => 'Agencia',
    'cuentaBancaria' => 'CuentaBancaria',
    'cuentaCtb' => 'CuentaCtb',
    'acumIva' => 'AcumIva',
    'ultimaCompra' => 'UltimaCompra',
    'observaciones' => 'Observaciones',
    'observacionesInternas' => 'ObservacionesInternas',
    'tarifa' => 'Tarifa',
    'tiendaCodigo' => 'Empresa',
    'facturacionDesglosada' => 'FacturacionDesglosada',
    'cuentaCtb2' => 'CuentaCtb2',
    'cuentaCtbIta' => 'CuentaCtbIta',
    'naturaleza' => 'Naturaleza',
    'ruta' => 'Ruta',
    'limiteCredito' => 'LimiteCredito',
    'portes' => 'Portes',
    'tarifaTrans' => 'TarifaTrans',
    'transportista' => 'Transportista',
    'propaganda' => 'Propaganda',
    'generarTraspaso' => 'GenerarTraspaso',
    'almacenTraspaso' => 'AlmacenTraspaso',
    'saldo' => 'Saldo',
    'fechaNacimiento' => 'FechaNacimiento',
    'acumuladoVenta' => 'AcumuladoVenta',
    'pjeFidelizacion' => 'PjeFidelizacion',
    'acumuladoFidelizacion' => 'AcumuladoFidelizacion',
    'fechaAltaFidelizacion' => 'FechaAltaFidelizacion',
    'copiasFactura' => 'CopiasFactura',
    'sexo' => 'Sexo',
    'tarjetaFidelizacion' => 'TarjetaFidelizacion',
    'banco' => 'Banco',
    'descripcionPago' => 'DescripcionPago',
    'obserRecibo' => 'ObserRecibo',
    'tipoDescuento' => 'TipoDescuento',
    'clasificacionComercial' => 'ClasificacionComercial',
    'tipologia' => 'Tipologia',
    'riesgoActualAdonix' => 'RiesgoActualAdonix',
    'acumuladoPuntos' => 'AcumuladoPuntos',
    'codigoPaisCliente' => 'CodigoPaisCliente',
    'codigoPaisDireccion' => 'CodigoPaisDireccion',
    'regimenImpuestos' => 'RegimenImpuestos',
    'swift' => 'Swift',
    'iban' => 'IBAN',
    'copiasFContado' => 'CopiasFContado',
    'retIrpf' => 'RetIrpf',
    'bloqueoVenta' => 'BloqueoVenta',
    'solicitarImpresionAlbaran' => 'SolicitarImpresionAlbaran',
    'preFacturacion' => 'PreFacturacion',
    'cobroContraSaldo' => 'CobroContraSaldo',
    'facturasEmail' => 'FacturasEmail',
    'tratamientoFiscal' => 'TratamientoFiscal',
    'tipoDescuentoFidelizacion' => 'TipoDescuentoFidelizacion',
    'interesesComerciales' => 'InteresesComerciales',
    'facturacionManual' => 'FacturacionManual',
    'empresaFacturacion' => 'EmpresaFacturacion',
    'proponerFactura' => 'ProponerFactura',
    'copiaImpresa' => 'CopiaImpresa',
    'certificarFacturas' => 'CertificarFacturas',
    'transporteDomicilio' => 'TransporteDomicilio',
    'pjeTransporte' => 'PjeTransporte',
    'pjeIVATransporte' => 'PjeIVATransporte',
    'referenciaMandato' => 'ReferenciaMandato',
    'fechaFirmaMandato' => 'FechaFirmaMandato',
    'agrupacionAgencia' => 'AgrupacionAgencia',
    'facturaE' => 'FacturaE',
    'oficinaContable' => 'OficinaContable',
    'organoGestor' => 'OrganoGestor',
    'unidadTramitadora' => 'UnidadTramitadora',
    'carnetManipulador' => 'CarnetManipulador',
    'fechaCaducidadCarnet' => 'FechaCaducidadCarnet',
    'asegurado' => 'Asegurado',
    'codigoTransaccionSII' => 'CodigoTransaccionSII',
    'organoProponente' => 'OrganoProponente',
    'profesional' => 'Profesional',
  ],
  /** CuentaCtb2 es float en [Clientes]; la cuenta contable no lleva decimales. */
  'intFields' => [
    'cuentaCtb2',
  ],
  /** No se persisten: el GET los sustituye por el calculo live de riesgo. */
  'readOnlyFields' => [
    'riesgoActualAdonix',
  ],
  'booleanFields' => [
    'swIva',
    'swRec',
    'facturacionDesglosada',
    'propaganda',
    'generarTraspaso',
    'retIrpf',
    'bloqueoVenta',
    'solicitarImpresionAlbaran',
    'preFacturacion',
    'cobroContraSaldo',
    'facturasEmail',
    'facturacionManual',
    'proponerFactura',
    'copiaImpresa',
    'certificarFacturas',
    'transporteDomicilio',
    'agrupacionAgencia',
    'facturaE',
    'asegurado',
    'profesional',
  ],
  'dateFields' => [
    'fechaAlta',
    'ultimaCompra',
    'fechaNacimiento',
    'fechaAltaFidelizacion',
    'fechaFirmaMandato',
    'fechaCaducidadCarnet',
  ],
  /**
   * Alta alineada con legacy: textos en '' (no NULL), numericos/bits a 0,
   * fechas vacias = 1995-01-01, Actividad 000, Pais Espana, Portes D, TratamientoFiscal N.
   */
  'createDefaults' => [
    'Actividad' => '000',
    'Pais' => 'España',
    'PaisEnvio' => 'España',
    'Portes' => 'D',
    'TratamientoFiscal' => 'N',
    'PersonaContacto' => '',
    'Direccion' => '',
    'Poblacion' => '',
    'Provincia' => '',
    'CodigoPostal' => '',
    'DireccionEnvio' => '',
    'PoblacionEnvio' => '',
    'ProvinciaEnvio' => '',
    'CodigoPostalEnvio' => '',
    'Telefono1' => '',
    'Telefono2' => '',
    'Fax' => '',
    'Email' => '',
    'EmailComercial' => '',
    'EmailFacturacion' => '',
    'Vendedor' => '',
    'AgenteOrigen' => '',
    'Agencia' => '',
    'CuentaBancaria' => '',
    'CuentaCtb' => '',
    'CuentaCtbIta' => '',
    'CuentaCtb2' => 0,
    'Observaciones' => '',
    'ObservacionesInternas' => '',
    'RazonSocial2' => '',
    'Swift' => '',
    'IBAN' => '',
    'Banco' => '',
    'DescripcionPago' => '',
    'ObserRecibo' => '',
    'InteresesComerciales' => '',
    'Transportista' => '',
    'TarjetaFidelizacion' => '',
    'TipoDescuento' => '',
    'TipoDescuentoFidelizacion' => '',
    'ClasificacionComercial' => '',
    'Tipologia' => '',
    'CodigoPaisCliente' => '',
    'CodigoPaisDireccion' => '',
    'RegimenImpuestos' => '',
    'CodigoDireccion' => '',
    'CodigoClienteEmpresa' => '',
    'EmpresaFacturacion' => '',
    'ReferenciaMandato' => '',
    'OficinaContable' => '',
    'OrganoGestor' => '',
    'UnidadTramitadora' => '',
    'OrganoProponente' => '',
    'CarnetManipulador' => '',
    'CodigoTransaccionSII' => '',
    'FidPregunta1' => '',
    'FidPregunta2' => '',
    'FidPregunta3' => '',
    'FidPregunta4' => '',
    'FidPregunta5' => '',
    'Sexo' => '',
    'Naturaleza' => 0,
    'LimiteCredito' => 0,
    'TarifaTrans' => 0,
    'AlmacenTraspaso' => 0,
    'NumeroSubvenciones' => 0,
    'SaldoMenuDiario' => 0,
    'AdressId' => 0,
    'Dto1' => 0,
    'Dto2' => 0,
    'Dto3' => 0,
    'Escalado' => 0,
    'DiaPago1' => 0,
    'DiaPago2' => 0,
    'Tarifa' => 0,
    'Ruta' => 0,
    'AcumIva' => 0,
    'AcumuladoVenta' => 0,
    'PjeFidelizacion' => 0,
    'AcumuladoFidelizacion' => 0,
    'CopiasFactura' => 0,
    'CopiasFContado' => 0,
    'AcumuladoPuntos' => 0,
    'Saldo' => 0,
    'RiesgoActualAdonix' => 0,
    'PjeTransporte' => 0,
    'PjeIVATransporte' => 0,
    'SW_IVA' => 1,
    'SW_Rec' => 0,
    'FacturacionDesglosada' => 0,
    'Propaganda' => 0,
    'GenerarTraspaso' => 0,
    'RetIrpf' => 0,
    'BloqueoVenta' => 0,
    'SolicitarImpresionAlbaran' => 0,
    'PreFacturacion' => 0,
    'CobroContraSaldo' => 0,
    'FacturasEmail' => 0,
    'FacturacionManual' => 0,
    'ProponerFactura' => 0,
    'CopiaImpresa' => 0,
    'CertificarFacturas' => 0,
    'TransporteDomicilio' => 0,
    'AgrupacionAgencia' => 0,
    'FacturaE' => 0,
    'Asegurado' => 0,
    'Profesional' => 0,
    // Sentinel legacy para fechas sin valor real.
    'UltimaCompra' => '1995-01-01 00:00:00',
    'FechaFirmaMandato' => '1995-01-01 00:00:00',
    'FechaCaducidadCarnet' => '1995-01-01 00:00:00',
    'FechaTx3' => '1995-01-01 00:00:00',
    'FechaEntradaAdonix' => '1995-01-01 00:00:00',
    'FechaAltaFidelizacion' => '1995-01-01 00:00:00',
    'UltimaSubvencion' => '1995-01-01 00:00:00',
  ],
];
