<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Clientes] (ficha completa estilo legacy).
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'fechaAlta' => 'FechaAlta',
    'activo' => 'Baja',
    'nombre' => 'RazonSocial',
    'razonSocial2' => 'RazonSocial2',
    'actividad' => 'Actividad',
    'nif' => 'NIF',
    'personaContacto' => 'PersonaContacto',
    'direccion' => 'Direccion',
    'poblacion' => 'Poblacion',
    'provincia' => 'Provincia',
    'pais' => 'Pais',
    'codigoPostal' => 'CodigoPostal',
    'telefono1' => 'Telefono1',
    'telefono2' => 'Telefono2',
    'fax' => 'Fax',
    'direccionEnvio' => 'DireccionEnvio',
    'poblacionEnvio' => 'PoblacionEnvio',
    'codigoPostalEnvio' => 'CodigoPostalEnvio',
    'provinciaEnvio' => 'ProvinciaEnvio',
    'paisEnvio' => 'PaisEnvio',
    'email' => 'Email',
    'emailComercial' => 'EmailComercial',
    'emailFacturacion' => 'EmailFacturacion',
    'dto1' => 'Dto1',
    'dto2' => 'Dto2',
    'dto3' => 'Dto3',
    'escalado' => 'Escalado',
    'swIva' => 'SW_IVA',
    'swRec' => 'SW_Rec',
    'vendedor' => 'Vendedor',
    'agenteOrigen' => 'AgenteOrigen',
    'formaPago' => 'FormaPago',
    'diaPago1' => 'DiaPago1',
    'diaPago2' => 'DiaPago2',
    'agencia' => 'Agencia',
    'cuentaBancaria' => 'CuentaBancaria',
    'cuentaCtb' => 'CuentaCtb',
    'acumIva' => 'AcumIva',
    'ultimaCompra' => 'UltimaCompra',
    'observaciones' => 'Observaciones',
    'observacionesInternas' => 'ObservacionesInternas',
    'tarifa' => 'Tarifa',
    'tiendaCodigo' => 'Empresa',
    'facturacionDesglosada' => 'FacturacionDesglosada',
    'cuentaCtb2' => 'CuentaCtb2',
    'cuentaCtbIta' => 'CuentaCtbIta',
    'naturaleza' => 'Naturaleza',
    'ruta' => 'Ruta',
    'limiteCredito' => 'LimiteCredito',
    'portes' => 'Portes',
    'tarifaTrans' => 'TarifaTrans',
    'transportista' => 'Transportista',
    'propaganda' => 'Propaganda',
    'generarTraspaso' => 'GenerarTraspaso',
    'almacenTraspaso' => 'AlmacenTraspaso',
    'saldo' => 'Saldo',
    'fechaNacimiento' => 'FechaNacimiento',
    'acumuladoVenta' => 'AcumuladoVenta',
    'pjeFidelizacion' => 'PjeFidelizacion',
    'acumuladoFidelizacion' => 'AcumuladoFidelizacion',
    'copiasFactura' => 'CopiasFactura',
    'sexo' => 'Sexo',
    'tarjetaFidelizacion' => 'TarjetaFidelizacion',
    'banco' => 'Banco',
    'descripcionPago' => 'DescripcionPago',
    'obserRecibo' => 'ObserRecibo',
    'tipoDescuento' => 'TipoDescuento',
    'clasificacionComercial' => 'ClasificacionComercial',
    'tipologia' => 'Tipologia',
    'riesgoActualAdonix' => 'RiesgoActualAdonix',
    'acumuladoPuntos' => 'AcumuladoPuntos',
    'codigoPaisCliente' => 'CodigoPaisCliente',
    'codigoPaisDireccion' => 'CodigoPaisDireccion',
    'regimenImpuestos' => 'RegimenImpuestos',
    'swift' => 'Swift',
    'iban' => 'IBAN',
    'copiasFContado' => 'CopiasFContado',
    'retIrpf' => 'RetIrpf',
    'bloqueoVenta' => 'BloqueoVenta',
    'solicitarImpresionAlbaran' => 'SolicitarImpresionAlbaran',
    'preFacturacion' => 'PreFacturacion',
    'cobroContraSaldo' => 'CobroContraSaldo',
    'facturasEmail' => 'FacturasEmail',
    'tratamientoFiscal' => 'TratamientoFiscal',
    'tipoDescuentoFidelizacion' => 'TipoDescuentoFidelizacion',
    'interesesComerciales' => 'InteresesComerciales',
    'facturacionManual' => 'FacturacionManual',
    'empresaFacturacion' => 'EmpresaFacturacion',
    'proponerFactura' => 'ProponerFactura',
    'copiaImpresa' => 'CopiaImpresa',
    'certificarFacturas' => 'CertificarFacturas',
    'transporteDomicilio' => 'TransporteDomicilio',
    'pjeTransporte' => 'PjeTransporte',
    'pjeIVATransporte' => 'PjeIVATransporte',
    'referenciaMandato' => 'ReferenciaMandato',
    'fechaFirmaMandato' => 'FechaFirmaMandato',
    'agrupacionAgencia' => 'AgrupacionAgencia',
    'facturaE' => 'FacturaE',
    'oficinaContable' => 'OficinaContable',
    'organoGestor' => 'OrganoGestor',
    'unidadTramitadora' => 'UnidadTramitadora',
    'carnetManipulador' => 'CarnetManipulador',
    'fechaCaducidadCarnet' => 'FechaCaducidadCarnet',
    'asegurado' => 'Asegurado',
    'codigoTransaccionSII' => 'CodigoTransaccionSII',
    'organoProponente' => 'OrganoProponente',
    'profesional' => 'Profesional',
  ],
  'booleanFields' => [
    'swIva',
    'swRec',
    'facturacionDesglosada',
    'propaganda',
    'generarTraspaso',
    'retIrpf',
    'bloqueoVenta',
    'solicitarImpresionAlbaran',
    'preFacturacion',
    'cobroContraSaldo',
    'facturasEmail',
    'facturacionManual',
    'proponerFactura',
    'copiaImpresa',
    'certificarFacturas',
    'transporteDomicilio',
    'agrupacionAgencia',
    'facturaE',
    'asegurado',
    'profesional',
  ],
  'dateFields' => [
    'fechaAlta',
    'ultimaCompra',
    'fechaNacimiento',
    'fechaFirmaMandato',
    'fechaCaducidadCarnet',
  ],
];
