<?php

declare(strict_types=1);

$tiendasConfig = require __DIR__ . '/tiendas-fields.php';

$puestosConfig = require __DIR__ . '/puestos-fields.php';

$articulosConfig = require __DIR__ . '/articulos-fields.php';

$clientesConfig = require __DIR__ . '/clientes-fields.php';

$proveedoresConfig = require __DIR__ . '/proveedores-fields.php';

return [
  'tiendas' => array_merge([
    'table' => 'Empresas',
    'primaryKey' => 'Codigo',
    'modulo' => 'tiendas',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre', 'NIF', 'NombreFiscal'],
  ], $tiendasConfig),
  'usuarios' => [
    'table' => 'Usuarios',
    'primaryKey' => 'Codigo',
    'modulo' => 'usuarios',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'rolCodigo' => 'Rol',
      'password' => 'PassWord',
      'activo' => 'Baja',
    ],
    'stringMaxLengths' => [
      'Codigo' => 20,
      'Nombre' => 50,
    ],
  ],
  'roles' => [
    'table' => 'Roles',
    'primaryKey' => 'Codigo',
    'modulo' => 'roles',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'activo' => 'Baja',
    ],
    'stringMaxLengths' => [
      'Codigo' => 10,
      'Nombre' => 50,
    ],
  ],
  'trabajadores' => [
    'table' => 'Vendedores',
    'primaryKey' => 'Codigo',
    'modulo' => 'trabajadores',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'comision' => 'ComisionVenta',
      'agente' => 'Agente',
      'vendedor' => 'Vendedor',
      'operario' => 'Operario',
      'tecnico' => 'Tecnico',
      'observaciones' => 'Comentario',
      'usuarioCodigo' => 'Usuario',
      'tarjeta' => 'Tarjeta',
      'conceptoDescuadre' => 'ConceptoDescuadre',
      'horaInicio' => 'HoraInicio',
      'horaFinal' => 'HoraFinal',
      'horaInicio2' => 'HoraInicio2',
      'horaFinal2' => 'HoraFinal2',
      'activo' => 'Baja',
    ],
    'hidden' => ['password'],
    'writeOnly' => ['password' => 'PassWord'],
    'booleanFields' => ['agente', 'vendedor', 'operario', 'tecnico'],
    'timeFields' => ['horaInicio', 'horaFinal', 'horaInicio2', 'horaFinal2'],
    'stringMaxLengths' => [
      'Codigo' => 4,
      'Nombre' => 50,
      'Usuario' => 6,
      'ConceptoDescuadre' => 2,
    ],
    /** Alinear alta con defaults SQL / legacy (bits 0, comision/tarjeta 0). */
    'createDefaults' => [
      'ComisionVenta' => 0,
      'Agente' => 0,
      'Vendedor' => 0,
      'Operario' => 0,
      'Tecnico' => 0,
      'Tarjeta' => 0,
      'MiniBar' => 0,
    ],
  ],
  'puestos-trabajo' => array_merge([
    'table' => 'Puestos',
    'primaryKey' => 'Puesto',
    'modulo' => 'puestos-trabajo',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Puesto', 'Descripcion'],
  ], $puestosConfig),
  'articulos' => array_merge([
    'table' => 'Articulos',
    'primaryKey' => 'Codigo',
    'modulo' => 'articulos',
    'softDelete' => ['column' => 'FechaBaja', 'inactiveValue' => 'NOT_NULL', 'activeValue' => null],
    'searchColumns' => ['Codigo', 'Descripcion', 'Alternativo'],
  ], $articulosConfig),
  'actividades' => [
    'table' => 'Actividades',
    'primaryKey' => 'Codigo',
    'modulo' => 'actividades',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'createDefaults' => [
      'Descripcion' => '',
    ],
  ],
  'intereses-comerciales' => [
    'table' => 'InteresesComerciales',
    'primaryKey' => 'Codigo',
    'modulo' => 'intereses-comerciales',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'createDefaults' => [
      'Descripcion' => '',
    ],
  ],
  'tipos-calculo-fidelizacion' => [
    'table' => 'TiposCalculoFidelizacion',
    'primaryKey' => 'Codigo',
    // Catálogo auxiliar de Clientes: reutiliza sus permisos (spec FR-010).
    'modulo' => 'clientes',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre', 'Motor'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'motor' => 'Motor',
      'factor' => 'Factor',
      'configuracion' => 'Configuracion',
      'activo' => 'Baja',
    ],
    'stringMaxLengths' => [
      'Codigo' => 20,
      'Nombre' => 50,
      'Motor' => 30,
    ],
    'createDefaults' => [
      'Nombre' => '',
      'Motor' => 'EUROS',
      'Factor' => 1,
      'Configuracion' => '',
      'Baja' => 0,
    ],
  ],
  'clientes' => array_merge([
    'table' => 'Clientes',
    'primaryKey' => 'Codigo',
    'modulo' => 'clientes',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'RazonSocial', 'NIF'],
  ], $clientesConfig),
  'proveedores' => array_merge([
    'table' => 'Proveedores',
    'primaryKey' => 'Codigo',
    'modulo' => 'proveedores',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'RazonSocial', 'NIF'],
  ], $proveedoresConfig),
  'almacenes' => [
    'table' => 'Almacenes',
    'primaryKey' => 'Codigo',
    'primaryKeyType' => 'int',
    'modulo' => 'almacenes',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'externo' => 'Externo',
      'reservaDirecta' => 'ReservaDirecta',
      'central' => 'Central',
      'traspasoAutomatico' => 'TraspasoAutomatico',
      'centroCoste' => 'CentroCoste',
      'gastos' => 'Gastos',
      'consolidaStockWeb' => 'ConsolidaStockWeb',
      'activo' => 'Baja',
    ],
    'booleanFields' => [
      'externo', 'reservaDirecta', 'central', 'traspasoAutomatico', 'gastos', 'consolidaStockWeb', 'activo',
    ],
    'stringMaxLengths' => [
      'Descripcion' => 40,
      'CentroCoste' => 10,
    ],
    /** Bits a 0; CentroCoste en blanco (''), no NULL. */
    'createDefaults' => [
      'Externo' => 0,
      'ReservaDirecta' => 0,
      'Central' => 0,
      'TraspasoAutomatico' => 0,
      'Gastos' => 0,
      'ConsolidaStockWeb' => 0,
      'CentroCoste' => '',
    ],
  ],
  'macrofamilias' => [
    'table' => 'MacroFamilias',
    'primaryKey' => 'Codigo',
    'modulo' => 'macrofamilias',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'stringMaxLengths' => [
      'Codigo' => 6,
      'Descripcion' => 40,
    ],
  ],
  'familias' => [
    'table' => 'Familias',
    'primaryKey' => 'Codigo',
    'modulo' => 'familias',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion', 'MacroFamilia'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'macroFamiliaCodigo' => 'MacroFamilia',
      'cuentaCtb' => 'CuentaCtb',
      'cuentaCtbIta' => 'CuentaCtbIta',
      'idWeb' => 'idWeb',
      'ctaTraspasoEntrada' => 'CtaTraspasoEntrada',
      'ctaTraspasoSalida' => 'CtaTraspasoSalida',
    ],
    'stringMaxLengths' => [
      'Codigo' => 6,
      'Descripcion' => 40,
      'MacroFamilia' => 6,
      'CuentaCtbIta' => 6,
    ],
    'createDefaults' => [
      'CuentaCtb' => 0,
      'CuentaCtbIta' => '',
      'idWeb' => 0,
      'CtaTraspasoEntrada' => 0,
      'CtaTraspasoSalida' => 0,
    ],
  ],
  'subfamilias' => [
    'table' => 'Subfamilias',
    'primaryKey' => 'Subfamilia',
    'modulo' => 'subfamilias',
    'hardDelete' => true,
    'searchColumns' => ['Subfamilia', 'Descripción', 'Familia'],
    'fields' => [
      'codigo' => 'Subfamilia',
      'descripcion' => 'Descripción',
      'familiaCodigo' => 'Familia',
      'cuentaCtb' => 'CuentaCtb',
      'idWeb' => 'idWeb',
      'idWeb2' => 'idWeb2',
      'idWeb3' => 'idWeb3',
      'idWeb4' => 'idWeb4',
      'ctaTraspasoEntrada' => 'CtaTraspasoEntrada',
      'ctaTraspasoSalida' => 'CtaTraspasoSalida',
    ],
    'stringMaxLengths' => [
      'Subfamilia' => 6,
      'Descripción' => 40,
      'Familia' => 6,
    ],
    'createDefaults' => [
      'CuentaCtb' => 0,
      'idWeb' => 0,
      'idWeb2' => 0,
      'idWeb3' => 0,
      'idWeb4' => 0,
      'CtaTraspasoEntrada' => 0,
      'CtaTraspasoSalida' => 0,
    ],
  ],
  'secciones' => [
    'table' => 'Secciones',
    'primaryKey' => 'Codigo',
    'modulo' => 'secciones',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'subFamiliaCodigo' => 'SubFamilia',
    ],
    'stringMaxLengths' => [
      'Codigo' => 6,
      'Descripcion' => 50,
      'SubFamilia' => 6,
    ],
    'createDefaults' => [
      'Descripcion' => '',
      'SubFamilia' => '',
    ],
  ],
  'subsecciones' => [
    'table' => 'SubSecciones',
    'primaryKey' => 'Codigo',
    'modulo' => 'subsecciones',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'stringMaxLengths' => [
      'Codigo' => 6,
      'Descripcion' => 50,
    ],
    'createDefaults' => [
      'Descripcion' => '',
    ],
  ],
  'agrupaciones' => [
    'table' => 'Agrupaciones',
    'primaryKey' => 'Codigo',
    'modulo' => 'agrupaciones',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'stringMaxLengths' => [
      'Codigo' => 6,
      'Descripcion' => 50,
    ],
  ],
  'impuestos' => [
    'table' => 'Impuestos',
    'primaryKey' => 'Codigo',
    'modulo' => 'impuestos',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion'],
    'booleanFields' => ['regimenEspecialAGYP', 'ivaExento'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'porcentajeIVA' => 'PjeIVA',
      'porcentajeRec' => 'PjeRec',
      'cuentaCtb' => 'CuentaCtb',
      'cuentaCtbSoportadoIntra' => 'CuentaCtbSoportadoIntra',
      'cuentaCtbRepercutidoIntra' => 'CuentaCtbRepercutidoIntra',
      'idWeb' => 'idWeb',
      'regimenEspecialAGYP' => 'RegimenEspecialAGYP',
      'ivaExento' => 'IvaExento',
      'activo' => 'Baja',
    ],
    'stringMaxLengths' => [
      'Codigo' => 2,
      'Descripcion' => 40,
    ],
    /** Legacy: % a 0, cuentas a 0, bits a 0; CuentaCtbIta* en blanco (''). */
    'createDefaults' => [
      'PjeIVA' => 0,
      'PjeRec' => 0,
      'CuentaCtb' => 0,
      'CuentaCtbSoportadoIntra' => 0,
      'CuentaCtbRepercutidoIntra' => 0,
      'idWeb' => 0,
      'RegimenEspecialAGYP' => 0,
      'IvaExento' => 0,
      'CuentaCtbIta' => '',
      'CuentaCtbIta2' => '',
    ],
  ],
  'formas-pago' => [
    'table' => 'FormasPago',
    'primaryKey' => 'Codigo',
    'modulo' => 'formas-pago',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion', 'Abreviacion'],
    'booleanFields' => [
      'cobroDeArqueo',
      'abrirCajon',
      'vales',
      'chipAcumuladoMenu',
      'tarjetaMonedero',
      'datafono',
      'emv',
      'cobroEnTienda',
      'cajonElectronico',
      'facturacionDirecta',
      'controlPagare',
      'fPagoActivaConPermiso',
      'facteTransferencia',
      'facteReciboDom',
    ],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'abreviacion' => 'Abreviacion',
      'cambio' => 'Cambio',
      'decimales' => 'Decimales',
      'numVtos' => 'NumVtos',
      'dias1erVto' => 'Dias1erVto',
      'diasEntreVtos' => 'DiasEntreVtos',
      'copiasTicket' => 'CopiasTicket',
      'orden' => 'OrdenAparicionVenta',
      'cobroDeArqueo' => 'CobroDeArqueo',
      'abrirCajon' => 'AbrirCajon',
      'vales' => 'Vales',
      'chipAcumuladoMenu' => 'ChipAcumuladoMenu',
      'tarjetaMonedero' => 'TarjetaMonedero',
      'datafono' => 'Datafono',
      'emv' => 'EMV',
      'cobroEnTienda' => 'CobroEnTienda',
      'cajonElectronico' => 'CajonElectronico',
      'facturacionDirecta' => 'FacturacionDirecta',
      'controlPagare' => 'ControlPagare',
      'fPagoActivaConPermiso' => 'FPagoActivaConPermiso',
      'tipo' => 'Tipo',
      'agrupacion' => 'Agrupacion',
      'cobroPago' => 'CobroPago',
      'cuentaCtb' => 'CuentaCtb',
      'nota' => 'Nota',
      'facteFpCodigo' => 'FACTEFPCodigo',
      'facteTransferencia' => 'FACTETransferencia',
      'facteReciboDom' => 'FACTEReciboDom',
      'facteIban' => 'FACTEIban',
      'facteBanco' => 'FACTEBanco',
      'facteSucursal' => 'FACTESucursal',
      'facteBanDir' => 'FACTEBanDir',
      'facteBanCodPos' => 'FACTEBanCodPos',
      'facteBanPob' => 'FACTEBanPob',
      'facteBanPrv' => 'FACTEBanPrv',
      'facteBanPai' => 'FACTEBanPai',
      'activo' => 'Baja',
    ],
    'stringMaxLengths' => [
      'Codigo' => 2,
      'Descripcion' => 40,
      'Abreviacion' => 3,
    ],
    /**
     * Legacy (alta tipica): numericos/bits a 0; textos FACTE/Tipo/Abreviacion/Nota en '' (no NULL).
     * Cambio/Decimales los rellena el cliente (1/2 como el resto de formas activas).
     */
    'createDefaults' => [
      'Cambio' => 1,
      'Decimales' => 2,
      'NumVtos' => 0,
      'Dias1erVto' => 0,
      'DiasEntreVtos' => 0,
      'DtoPPgo' => 0,
      'RecFinan' => 0,
      'CobroDeArqueo' => 0,
      'Vales' => 0,
      'Agrupacion' => 0,
      'Chip' => 0,
      'AbrirCajon' => 0,
      'TarjetaMonedero' => 0,
      'Datafono' => 0,
      'CopiasTicket' => 0,
      'ChipAcumuladoMenu' => 0,
      'CobroEnTienda' => 0,
      'EMV' => 0,
      'GenerarTraspaso' => 0,
      'CajonElectronico' => 0,
      'FacturacionDirecta' => 0,
      'FACTEFPCodigo' => 0,
      'FACTETransferencia' => 0,
      'FACTEReciboDom' => 0,
      'ControlPagare' => 0,
      'OrdenAparicionVenta' => 0,
      'FPagoActivaConPermiso' => 0,
      'Abreviacion' => '',
      'Tipo' => '',
      'Nota' => '',
      'FACTEIban' => '',
      'FACTEBanco' => '',
      'FACTESucursal' => '',
      'FACTEBanDir' => '',
      'FACTEBanCodPos' => '',
      'FACTEBanPob' => '',
      'FACTEBanPrv' => '',
      'FACTEBanPai' => '',
    ],
  ],
  'bancos' => [
    'table' => 'Bancos',
    'primaryKey' => 'Codigo',
    'modulo' => 'proveedores',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'domicilio' => 'Domicilio',
      'poblacion' => 'Poblacion',
      'codigoPostal' => 'CodigoPostal',
      'provincia' => 'Provincia',
      'cuenta' => 'Cuenta',
      'sufijo' => 'Sufijo',
    ],
    'stringMaxLengths' => [
      'Codigo' => 9,
      'Nombre' => 50,
      'Domicilio' => 50,
      'Poblacion' => 50,
      'CodigoPostal' => 8,
      'Provincia' => 50,
      'Cuenta' => 23,
    ],
  ],
  /** Plan contable completo. */
  'cuentas' => [
    'table' => 'Cuentas',
    'primaryKey' => 'Codigo',
    'modulo' => 'proveedores',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'stringMaxLengths' => [
      'Codigo' => 10,
      'Descripcion' => 40,
    ],
  ],
  /**
   * Cuentas de banco: equivalente a la consulta legacy "CuentasBan" (ficha
   * Proveedores → campo Banco). Solo cuentas de ultimo nivel del subgrupo 572
   * (bancos c/c a la vista del PGC), que es lo que lista el buscador legacy.
   */
  'cuentas-banco' => [
    'table' => 'Cuentas',
    'primaryKey' => 'Codigo',
    'modulo' => 'proveedores',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fixedWhere' => "[Codigo] LIKE '572%' AND ISNULL([UltNivel], 0) = 1",
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
    'stringMaxLengths' => [
      'Codigo' => 10,
      'Descripcion' => 40,
    ],
  ],
];
