<?php

declare(strict_types=1);

$tiendasConfig = require __DIR__ . '/tiendas-fields.php';

$puestosConfig = require __DIR__ . '/puestos-fields.php';

$articulosConfig = require __DIR__ . '/articulos-fields.php';

$clientesConfig = require __DIR__ . '/clientes-fields.php';

$proveedoresConfig = require __DIR__ . '/proveedores-fields.php';

return [
  'tiendas' => array_merge([
    'table' => 'Empresas',
    'primaryKey' => 'Codigo',
    'modulo' => 'tiendas',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre', 'NIF', 'NombreFiscal'],
  ], $tiendasConfig),
  'usuarios' => [
    'table' => 'Usuarios',
    'primaryKey' => 'Codigo',
    'modulo' => 'usuarios',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'rolCodigo' => 'Rol',
      'activo' => 'Baja',
    ],
    'hidden' => ['password'],
    'writeOnly' => ['password' => 'PassWord'],
  ],
  'roles' => [
    'table' => 'Roles',
    'primaryKey' => 'Codigo',
    'modulo' => 'roles',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'activo' => 'Baja',
    ],
  ],
  'trabajadores' => [
    'table' => 'Vendedores',
    'primaryKey' => 'Codigo',
    'modulo' => 'trabajadores',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Nombre'],
    'fields' => [
      'codigo' => 'Codigo',
      'nombre' => 'Nombre',
      'comision' => 'ComisionVenta',
      'agente' => 'Agente',
      'vendedor' => 'Vendedor',
      'operario' => 'Operario',
      'tecnico' => 'Tecnico',
      'observaciones' => 'Comentario',
      'usuarioCodigo' => 'Usuario',
      'horaInicio' => 'HoraInicio',
      'horaFinal' => 'HoraFinal',
      'horaInicio2' => 'HoraInicio2',
      'horaFinal2' => 'HoraFinal2',
      'activo' => 'Baja',
    ],
    'hidden' => ['password'],
    'writeOnly' => ['password' => 'PassWord'],
    'booleanFields' => ['agente', 'vendedor', 'operario', 'tecnico'],
    'timeFields' => ['horaInicio', 'horaFinal', 'horaInicio2', 'horaFinal2'],
  ],
  'puestos-trabajo' => array_merge([
    'table' => 'Puestos',
    'primaryKey' => 'Puesto',
    'modulo' => 'puestos-trabajo',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Puesto', 'Descripcion'],
  ], $puestosConfig),
  'articulos' => array_merge([
    'table' => 'Articulos',
    'primaryKey' => 'Codigo',
    'modulo' => 'articulos',
    'softDelete' => ['column' => 'FechaBaja', 'inactiveValue' => 'NOT_NULL', 'activeValue' => null],
    'searchColumns' => ['Codigo', 'Descripcion', 'Alternativo'],
  ], $articulosConfig),
  'actividades' => [
    'table' => 'Actividades',
    'primaryKey' => 'Codigo',
    'modulo' => 'actividades',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
  ],
  'intereses-comerciales' => [
    'table' => 'InteresesComerciales',
    'primaryKey' => 'Codigo',
    'modulo' => 'intereses-comerciales',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
  ],
  'clientes' => array_merge([
    'table' => 'Clientes',
    'primaryKey' => 'Codigo',
    'modulo' => 'clientes',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'RazonSocial', 'NIF'],
  ], $clientesConfig),
  'proveedores' => array_merge([
    'table' => 'Proveedores',
    'primaryKey' => 'Codigo',
    'modulo' => 'proveedores',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'RazonSocial', 'NIF'],
  ], $proveedoresConfig),
  'almacenes' => [
    'table' => 'Almacenes',
    'primaryKey' => 'Codigo',
    'primaryKeyType' => 'int',
    'modulo' => 'almacenes',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'externo' => 'Externo',
      'reservaDirecta' => 'ReservaDirecta',
      'central' => 'Central',
      'traspasoAutomatico' => 'TraspasoAutomatico',
      'centroCoste' => 'CentroCoste',
      'gastos' => 'Gastos',
      'consolidaStockWeb' => 'ConsolidaStockWeb',
      'activo' => 'Baja',
    ],
    'booleanFields' => [
      'externo', 'reservaDirecta', 'central', 'traspasoAutomatico', 'gastos', 'consolidaStockWeb', 'activo',
    ],
  ],
  'macrofamilias' => [
    'table' => 'MacroFamilias',
    'primaryKey' => 'Codigo',
    'modulo' => 'macrofamilias',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
  ],
  'familias' => [
    'table' => 'Familias',
    'primaryKey' => 'Codigo',
    'modulo' => 'familias',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion', 'MacroFamilia'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'macroFamiliaCodigo' => 'MacroFamilia',
      'cuentaCtb' => 'CuentaCtb',
      'cuentaCtbIta' => 'CuentaCtbIta',
      'idWeb' => 'idWeb',
      'ctaTraspasoEntrada' => 'CtaTraspasoEntrada',
      'ctaTraspasoSalida' => 'CtaTraspasoSalida',
    ],
  ],
  'subfamilias' => [
    'table' => 'Subfamilias',
    'primaryKey' => 'Subfamilia',
    'modulo' => 'subfamilias',
    'hardDelete' => true,
    'searchColumns' => ['Subfamilia', 'Descripción', 'Familia'],
    'fields' => [
      'codigo' => 'Subfamilia',
      'descripcion' => 'Descripción',
      'familiaCodigo' => 'Familia',
      'cuentaCtb' => 'CuentaCtb',
      'idWeb' => 'idWeb',
      'idWeb2' => 'idWeb2',
      'idWeb3' => 'idWeb3',
      'idWeb4' => 'idWeb4',
      'ctaTraspasoEntrada' => 'CtaTraspasoEntrada',
      'ctaTraspasoSalida' => 'CtaTraspasoSalida',
    ],
  ],
  'agrupaciones' => [
    'table' => 'Agrupaciones',
    'primaryKey' => 'Codigo',
    'modulo' => 'agrupaciones',
    'hardDelete' => true,
    'searchColumns' => ['Codigo', 'Descripcion'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
    ],
  ],
  'impuestos' => [
    'table' => 'Impuestos',
    'primaryKey' => 'Codigo',
    'modulo' => 'impuestos',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion'],
    'booleanFields' => ['regimenEspecialAGYP', 'ivaExento'],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'porcentajeIVA' => 'PjeIVA',
      'porcentajeRec' => 'PjeRec',
      'cuentaCtb' => 'CuentaCtb',
      'cuentaCtbSoportadoIntra' => 'CuentaCtbSoportadoIntra',
      'cuentaCtbRepercutidoIntra' => 'CuentaCtbRepercutidoIntra',
      'idWeb' => 'idWeb',
      'regimenEspecialAGYP' => 'RegimenEspecialAGYP',
      'ivaExento' => 'IvaExento',
      'activo' => 'Baja',
    ],
  ],
  'formas-pago' => [
    'table' => 'FormasPago',
    'primaryKey' => 'Codigo',
    'modulo' => 'formas-pago',
    'softDelete' => ['column' => 'Baja', 'inactiveValue' => 1, 'activeValue' => 0],
    'searchColumns' => ['Codigo', 'Descripcion', 'Abreviacion'],
    'booleanFields' => [
      'cobroDeArqueo',
      'abrirCajon',
      'vales',
      'chipAcumuladoMenu',
      'tarjetaMonedero',
      'datafono',
      'emv',
      'cobroEnTienda',
      'cajonElectronico',
      'facturacionDirecta',
      'controlPagare',
      'fPagoActivaConPermiso',
      'facteTransferencia',
      'facteReciboDom',
    ],
    'fields' => [
      'codigo' => 'Codigo',
      'descripcion' => 'Descripcion',
      'abreviacion' => 'Abreviacion',
      'cambio' => 'Cambio',
      'decimales' => 'Decimales',
      'numVtos' => 'NumVtos',
      'dias1erVto' => 'Dias1erVto',
      'diasEntreVtos' => 'DiasEntreVtos',
      'copiasTicket' => 'CopiasTicket',
      'orden' => 'OrdenAparicionVenta',
      'cobroDeArqueo' => 'CobroDeArqueo',
      'abrirCajon' => 'AbrirCajon',
      'vales' => 'Vales',
      'chipAcumuladoMenu' => 'ChipAcumuladoMenu',
      'tarjetaMonedero' => 'TarjetaMonedero',
      'datafono' => 'Datafono',
      'emv' => 'EMV',
      'cobroEnTienda' => 'CobroEnTienda',
      'cajonElectronico' => 'CajonElectronico',
      'facturacionDirecta' => 'FacturacionDirecta',
      'controlPagare' => 'ControlPagare',
      'fPagoActivaConPermiso' => 'FPagoActivaConPermiso',
      'tipo' => 'Tipo',
      'agrupacion' => 'Agrupacion',
      'cobroPago' => 'CobroPago',
      'cuentaCtb' => 'CuentaCtb',
      'nota' => 'Nota',
      'facteFpCodigo' => 'FACTEFPCodigo',
      'facteTransferencia' => 'FACTETransferencia',
      'facteReciboDom' => 'FACTEReciboDom',
      'facteIban' => 'FACTEIban',
      'facteBanco' => 'FACTEBanco',
      'facteSucursal' => 'FACTESucursal',
      'facteBanDir' => 'FACTEBanDir',
      'facteBanCodPos' => 'FACTEBanCodPos',
      'facteBanPob' => 'FACTEBanPob',
      'facteBanPrv' => 'FACTEBanPrv',
      'facteBanPai' => 'FACTEBanPai',
      'activo' => 'Baja',
    ],
  ],
];
