<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Proveedores] (ficha completa estilo legacy).
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'nombre' => 'RazonSocial',
    'codigoCliente' => 'CodigoClte',
    'nif' => 'NIF',
    'personaContacto' => 'PersonaContacto',
    'direccion' => 'Direccion',
    'poblacion' => 'Poblacion',
    'codigoPostal' => 'CodigoPostal',
    'provincia' => 'Provincia',
    'pais' => 'Pais',
    'telefono1' => 'Telefono1',
    'telefono2' => 'Telefono2',
    'fax' => 'Fax',
    'dto' => 'Dto',
    'dto2' => 'Dto2',
    'dto3' => 'Dto3',
    'swIva' => 'SW_IVA',
    'swRec' => 'SW_Rec',
    'ivaAgrario' => 'IvaAgrario',
    'acumIva' => 'AcumIVA',
    'minSinPortes' => 'MinSinPortes',
    'notas' => 'Notas',
    'cuentaCtb' => 'CuentaCtb',
    'formaPago' => 'FormaPago',
    'email' => 'Email',
    'emailComercial' => 'EmailComercial',
    'emailFacturacion' => 'EmailFacturacion',
    'pedidosAutomaticos' => 'PedidosAutomaticos',
    'aecoc' => 'Aecoc',
    'codigoCentral' => 'CodigoCentral',
    'swift' => 'Swift',
    'iban' => 'IBAN',
    'tratamientoFiscal' => 'TratamientoFiscal',
    'diaPago1' => 'DiaPago1',
    'diaPago2' => 'DiaPago2',
    'coeficienteTransporte' => 'CoeficienteTransporte',
    'pasaporteFitosanitario' => 'PasaporteFitosanitario',
    'interesesComerciales' => 'InteresesComerciales',
    'direccionEnvio' => 'DireccionEnvio',
    'poblacionEnvio' => 'PoblacionEnvio',
    'codigoPostalEnvio' => 'CodigoPostalEnvio',
    'provinciaEnvio' => 'ProvinciaEnvio',
    'paisEnvio' => 'PaisEnvio',
    'codigoTransaccionSII' => 'CodigoTransaccionSII',
    'pedidosWeb' => 'PedidosWeb',
    'cuentaBanco' => 'CuentaBanco',
    'asociado' => 'Asociado',
    'claveFirma' => 'ClaveFirma',
    'lUpdate' => 'LUpdate',
    'activo' => 'Baja',
  ],
  'booleanFields' => [
    'swIva',
    'swRec',
    'ivaAgrario',
    'pedidosAutomaticos',
    'pedidosWeb',
    'asociado',
  ],
  'hidden' => ['lUpdate'],
];
