<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Puestos] (ficha completa).
 */
return [
  'fields' => [
    'codigo' => 'Puesto',
    'descripcion' => 'Descripcion',
    'tiendaCodigo' => 'EmpresaArqueo',
    'trabajadorCodigo' => 'Trabajador',
    'usuarioCodigo' => 'Usuario',
    'impresora80' => 'Impresora80',
    'impresoraTickets' => 'ImpresoraTickets',
    'impresoraAlbaranes' => 'ImpresoraAlbaranes',
    'impresoraFacturas' => 'ImpresoraFacturas',
    'cajon' => 'Cajon',
    'literal1' => 'Literal1',
    'literal2' => 'Literal2',
    'literal3' => 'Literal3',
    'literal4' => 'Literal4',
    'literal5' => 'Literal5',
    'literal6' => 'Literal6',
    'literal7' => 'Literal7',
    'literal8' => 'Literal8',
    'literal9' => 'Literal9',
    'impresoraRecibos' => 'ImpresoraRecibos',
    'ticketExpandido' => 'TicketExpandido',
    'ticketNegativo' => 'TicketNegativo',
    'ticketAutomatico' => 'TicketAutomatico',
    'impresoraPresupuestos' => 'ImpresoraPresupuestos',
    'impresoraFacturasContado' => 'ImpresoraFacturasContado',
    'formatoAlbaranes' => 'FormatoAlbaranes',
    'formatoFacturasContado' => 'FormatoFacturasContado',
    'formatoPresupuestos' => 'FormatoPresupuestos',
    'formatoFacturas' => 'FormatoFacturas',
    'formatoRecibos' => 'FormatoRecibos',
    'impresoraPedidos' => 'ImpresoraPedidos',
    'formatoPedidos' => 'FormatoPedidos',
    'fax' => 'Fax',
    'impresoraTicketsF' => 'ImpresoraTicketsF',
    'slipFactura' => 'SlipFactura',
    'numerodeLineas' => 'NumerodeLineas',
    'spaceSlip' => 'SpaceSlip',
    'lineasInicio' => 'LineasInicio',
    'lineasDeSalto' => 'LineasDeSalto',
    'balanza' => 'Balanza',
    'regresoaCajero' => 'RegresoaCajero',
    'tarifa' => 'Tarifa',
    'factura80' => 'Factura80',
    'cocina' => 'Cocina',
    'teclado' => 'Teclado',
    'saltoAutomatico' => 'SaltoAutomatico',
    'display' => 'Display',
    'impresionB' => 'ImpresionB',
    'impTicketIvaB' => 'ImpTicketIvaB',
    'impTicketIvaR' => 'ImpTicketIvaR',
    'impresionComprobanteB' => 'ImpresionComprobanteB',
    'impresionComprobanteR' => 'ImpresionComprobanteR',
    'radio' => 'Radio',
    'cierreAutomatico' => 'CierreAutomatico',
    'chip' => 'Chip',
    'impresoraEtiquetas' => 'ImpresoraEtiquetas',
    'dispositivoCajon' => 'DispositivoCajon',
    'ticketRestauranteAutomatico' => 'TicketRestauranteAutomatico',
    'impresoraEtiquetasEnvio' => 'ImpresoraEtiquetasEnvio',
    'formatoEtiquetasEnvio' => 'FormatoEtiquetasEnvio',
    'imp80' => 'Imp80',
    'impFax' => 'ImpFax',
    'impAlbaranes' => 'ImpAlbaranes',
    'impPresupuestos' => 'ImpPresupuestos',
    'impFacturasContado' => 'ImpFacturasContado',
    'impFacturas' => 'ImpFacturas',
    'impRecibos' => 'ImpRecibos',
    'impPedidos' => 'ImpPedidos',
    'impEtiquetasEnvio' => 'ImpEtiquetasEnvio',
    'terminalPDA' => 'TerminalPDA',
    'caracteresPorLinea' => 'CaracteresPorLinea',
    'paroMostrarCambio' => 'ParoMostrarCambio',
    'raton' => 'Raton',
    'copiasTicket' => 'CopiasTicket',
    'lectorTarjetas' => 'LectorTarjetas',
    'cambioCentroAutomatico' => 'CambioCentroAutomatico',
    'nvLogo' => 'NVLogo',
    'resolucionPda' => 'ResolucionPda',
    'datafono' => 'Datafono',
    'terminalDatafono' => 'TerminalDatafono',
    'calculoIvaB' => 'CalculoIvaB',
    'calculoIvaR' => 'CalculoIvaR',
    'scanerPortatil' => 'ScanerPortatil',
    'cambioAutomaticoMesasCentro' => 'CambioAutomaticoMesasCentro',
    'repeticionFacturaLiquidar' => 'RepeticionFacturaLiquidar',
    'ticketAperturaInicio' => 'TicketAperturaInicio',
    'capturaPedidos' => 'CapturaPedidos',
    'restauranteCtaDirecta' => 'RestauranteCtaDirecta',
    'contadorAuxiliar' => 'ContadorAuxiliar',
    'ultimoTrabajoAuxiliar' => 'UltimoTrabajoAuxiliar',
    'scaner' => 'Scaner',
    'scanerVelocidad' => 'ScanerVelocidad',
    'finalizacionScaner' => 'FinalizacionScaner',
    'impresoraTarjetas' => 'ImpresoraTarjetas',
    'impTarjetas' => 'ImpTarjetas',
    'impresoraAlbaranCompras' => 'ImpresoraAlbaranCompras',
    'impAlbaranCompras' => 'ImpAlbaranCompras',
    'formatoAlbaranCompras' => 'FormatoAlbaranCompras',
    'impresoraPedidoCompras' => 'ImpresoraPedidoCompras',
    'impPedidoCompras' => 'ImpPedidoCompras',
    'formatoPedidoCompras' => 'FormatoPedidoCompras',
    'cajonElectronico' => 'CajonElectronico',
    'seccion' => 'Seccion',
    'ultSesion' => 'UltSesion',
    'impresoraFabricacion' => 'ImpresoraFabricacion',
    'impFabricacion' => 'ImpFabricacion',
    'formatoFabricacion' => 'FormatoFabricacion',
    'impresoraCorte' => 'ImpresoraCorte',
    'impCorte' => 'ImpCorte',
    'formatoCorte' => 'FormatoCorte',
    'modoTablet' => 'ModoTablet',
    'urlQR' => 'UrlQR',
    'activo' => 'Baja',
  ],
  'booleanFields' => [
    'cajon', 'ticketExpandido', 'ticketNegativo', 'ticketAutomatico', 'slipFactura',
    'regresoaCajero', 'factura80', 'cocina', 'saltoAutomatico', 'impresionB',
    'impTicketIvaB', 'impTicketIvaR', 'impresionComprobanteB', 'impresionComprobanteR',
    'cierreAutomatico', 'ticketRestauranteAutomatico', 'terminalPDA', 'paroMostrarCambio',
    'raton', 'cambioCentroAutomatico', 'calculoIvaB', 'calculoIvaR',
    'cambioAutomaticoMesasCentro', 'repeticionFacturaLiquidar', 'ticketAperturaInicio',
    'capturaPedidos', 'restauranteCtaDirecta', 'contadorAuxiliar', 'ultimoTrabajoAuxiliar',
    'modoTablet', 'activo',
  ],
];
