<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Empresas] para ficha completa de tienda.
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'nombre' => 'Nombre',
    'nombreFiscal' => 'NombreFiscal',
    'codigoExterno' => 'CodigoExterno',
    'nif' => 'NIF',
    'direccion' => 'Direccion',
    'codigoPostal' => 'CodigoPostal',
    'poblacion' => 'Poblacion',
    'provincia' => 'Provincia',
    'pais' => 'Pais',
    'telefono1' => 'Telefono1',
    'telefono2' => 'Telefono2',
    'email' => 'EMail',
    'pasaporteFitosanitario' => 'PasaporteFitosanitario',
    'almacenCodigo' => 'Almacen',
    'literalFacturaDiferida' => 'LiteralFactura',
    'literalFacturaContado' => 'LiteralFacturaContado',
    'literalPresupuesto' => 'LiteralPresupuesto',
    'literalVale' => 'LiteralVale',
    'literalTicket' => 'LiteralTicket',
    'codIvaSuperReducido' => 'CodIvaSuperReducido',
    'codIvaReducido' => 'CodIvaReducido',
    'codIvaNormal' => 'CodIvaNormal',
    'codIvaIncrementado' => 'CodIvaIncrementado',
    'codIvaEsp5' => 'CodIvaEsp5',
    'codIvaEsp6' => 'CodIvaEsp6',
    'swIva' => 'SW_IVA',
    'recargo' => 'Recargo',
    'regimenCanario' => 'RegimenCanario',
    'intPreciosIvaIncluido' => 'IntPreciosIvaIncludo',
    'divisa' => 'Divisa',
    'divisaAlt' => 'DivisaAlt',
    'dto' => 'Dto',
    'sumarDescuento' => 'SumarDescuento',
    'bloqueoFidelizacion' => 'BloqueoFidelizacion',
    'pjeRetIrpf' => 'PjeRetIrpf',
    'ctbRetIrpf' => 'CtbRetIrpf',
    'centroCoste' => 'CentroCoste',
    'solicitarPerfil' => 'SolicitarPerfil',
    'tarifa' => 'Tarifa',
    'datos' => 'Datos',
    'prefijo' => 'Prefijo',
    'serieFacturas' => 'SerieFacturas',
    'facturasRectificativas' => 'FacturasRectificativas',
    'serieAbonos' => 'SerieAbonos',
    'minimoFidelizacion' => 'MinimoFidelizacion',
    'valesEmitidos' => 'Vales_Em',
    'valesRecibidos' => 'Vales_Re',
    'esCentral' => 'Central',
    'facturaLaCentral' => 'FacturaLaCentral',
    'comunicaCentral' => 'ComunicaCentral',
    'unidadComunicacion' => 'UnidadComunicacion',
    'almacenesInternos' => 'AlmacenesInternos',
    'conexionOnline' => 'ConexionOnline',
    'avisoStockCero' => 'AvisoStockCero',
    'dtoSiCambioPrecio' => 'DtoSiCambioPrecio',
    'impTicketInc' => 'ImpTicketInc',
    'desglosarBasesTicketIvaInc' => 'DesglosarBasesTicketIvaInc',
    'imprimirCodigoArticulo' => 'ImprimirCodigoArticulo',
    'obligarDineroEntregado' => 'ObligarDineroEntregado',
    'impSaldoTicket' => 'ImpSaldoTicket',
    'crearReciboCredito' => 'CrearReciboCredito',
    'aecoc' => 'Aecoc',
    'genBarras' => 'GenBarras',
    'genDesdeCodigo' => 'GenDesdeCodigo',
    'genClientes' => 'GenClientes',
    'genArticulos' => 'GenArticulos',
    'genProveedores' => 'GenProveedores',
    'articuloMantenimiento' => 'ArticuloMantenimiento',
    'controlVales' => 'ControlVales',
    'minimoCambioVales' => 'MinimoCambioVales',
    'importeObligatorioFactura' => 'ImporteObligatorioFactura',
    'tarifa1Escalado' => 'Tarifa1Escalado',
    'tarifa2Escalado' => 'Tarifa2Escalado',
    'tarifa3Escalado' => 'Tarifa3Escalado',
    'tarifa4Escalado' => 'Tarifa4Escalado',
    'tarifa5Escalado' => 'Tarifa5Escalado',
    'tarifa6Escalado' => 'Tarifa6Escalado',
    'tarifa7Escalado' => 'Tarifa7Escalado',
    'tarifa8Escalado' => 'Tarifa8Escalado',
    'tarifa9Escalado' => 'Tarifa9Escalado',
    'checkProveedor' => 'CheckProveedor',
    'impAlternativo' => 'ImpAlternativo',
    'cambiaProveedor' => 'CambiaProveedor',
    'maximizarListado' => 'MaximizarListado',
    'copiasAlbaranReparto' => 'CopiasAlbaranReparto',
    'copiasAlbaran' => 'CopiasAlbaran',
    'copiasFactura' => 'CopiasFactura',
    'copiasFacturaReparto' => 'CopiasFacturaReparto',
    'copiasSimulacion' => 'CopiasSimulacion',
    'impEtiquetasSinEans' => 'ImpEtiquetasSinEans',
    'etiquetasIvaIncluido' => 'EtiquetasIvaIncluido',
    'impEtiquetasSoloEansPropios' => 'ImpEtiquetasSoloEansPropios',
    'decimalesPrecio' => 'DecimalesPrecio',
    'solicitarPerfilParam' => 'SolicitarPerfil',
    'desglosarEscandallo' => 'DesglosarEscandallo',
    'recalculoTarifas' => 'RecalculoTarifas',
    'literalInvitacion' => 'LiteralInvitacion',
    'atri0' => 'Atri0',
    'atri1' => 'Atri1',
    'atri2' => 'Atri2',
    'atri3' => 'Atri3',
    'atri4' => 'Atri4',
    'atri5' => 'Atri5',
    'atri6' => 'Atri6',
    'atri7' => 'Atri7',
    'atri8' => 'Atri8',
    'atri9' => 'Atri9',
    'colAtri0' => 'ColAtri0',
    'colAtri1' => 'ColAtri1',
    'colAtri2' => 'ColAtri2',
    'colAtri3' => 'ColAtri3',
    'colAtri4' => 'ColAtri4',
    'colAtri5' => 'ColAtri5',
    'colAtri6' => 'ColAtri6',
    'colAtri7' => 'ColAtri7',
    'colAtri8' => 'ColAtri8',
    'colAtri9' => 'ColAtri9',
    'appWeb' => 'AppWeb',
    'litPiePedidoCompra' => 'LitPiePedidoCompra',
    'pathExcelEstadisticas' => 'PathExcelEstadisticas',
    'centrarLiteralesAdicionales' => 'CentrarlLiteralesAdicionales',
    'literal6' => 'Literal6',
    'literal7' => 'Literal7',
    'literal8' => 'Literal8',
    'literal9' => 'Literal9',
    'literal10' => 'Literal10',
    'literal11' => 'Literal11',
    'literal12' => 'Literal12',
    'literal13' => 'Literal13',
    'literal14' => 'Literal14',
    'literal15' => 'Literal15',
    'literal16' => 'Literal16',
    'literal17' => 'Literal17',
    'literal18' => 'Literal18',
    'literal19' => 'Literal19',
    'literal20' => 'Literal20',
    'literal21' => 'Literal21',
    'literal22' => 'Literal22',
    'literal23' => 'Literal23',
    'literal24' => 'Literal24',
    'literal25' => 'Literal25',
    'ultPedidoCom' => 'UltPedidoCom',
    'ultAlbaranCom' => 'UltAlbaranCom',
    'ultAlbaranVen' => 'UltAlbaranVen',
    'ultAlbaranTra' => 'UltAlbaranTra',
    'ultTicket' => 'UltTicket',
    'ultFactura' => 'UltFactura',
    'ultFacturaDiferida' => 'UltFacturaDiferida',
    'ultPedidoCli' => 'UltPedidoCli',
    'ultEnvio' => 'UltEnvio',
    'ultEan' => 'UltEan',
    'ultCliente' => 'UltCliente',
    'ultAbono' => 'UltAbono',
    'ultAbonoDiferido' => 'UltAbonoDiferido',
    'ultProveedor' => 'UltProveedor',
    'ultPreFactura' => 'UltPreFactura',
    'ultOrdenFabricacion' => 'UltOrdenFabricacion',
    'ultTransacCajon' => 'UltTransacCajon',
    'ultFicheroRecepcion' => 'UltFicheroRecepcion',
    'ultFicheroRecepcionC' => 'UltFicheroRecepcionC',
    'activo' => 'Baja',
  ],
  'booleanFields' => [
    'esCentral', 'facturaLaCentral', 'comunicaCentral', 'almacenesInternos', 'conexionOnline',
    'avisoStockCero', 'dtoSiCambioPrecio', 'impTicketInc', 'desglosarBasesTicketIvaInc', 'imprimirCodigoArticulo',
    'obligarDineroEntregado', 'impSaldoTicket', 'crearReciboCredito', 'genBarras', 'genDesdeCodigo',
    'genClientes', 'genArticulos', 'genProveedores', 'controlVales', 'tarifa1Escalado', 'tarifa2Escalado',
    'tarifa3Escalado', 'tarifa4Escalado', 'tarifa5Escalado', 'tarifa6Escalado', 'tarifa7Escalado',
    'tarifa8Escalado', 'tarifa9Escalado', 'checkProveedor', 'impAlternativo', 'cambiaProveedor', 'maximizarListado',
    'impEtiquetasSinEans', 'impEtiquetasSoloEansPropios',
    'etiquetasIvaIncluido', 'desglosarEscandallo', 'appWeb', 'centrarLiteralesAdicionales',
    'swIva', 'recargo', 'regimenCanario', 'intPreciosIvaIncluido', 'sumarDescuento', 'bloqueoFidelizacion',
    'solicitarPerfil', 'solicitarPerfilParam', 'facturasRectificativas', 'activo',
  ],
  /** Campos numericos que en UI/negocio son enteros (aunque la columna sea real/float). */
  'intFields' => [
    'copiasAlbaranReparto',
    'copiasAlbaran',
    'copiasFactura',
    'copiasFacturaReparto',
    'copiasSimulacion',
    'decimalesPrecio',
    'impEtiquetasSinEans',
    'impEtiquetasSoloEansPropios',
    'literalInvitacion',
    'colAtri0', 'colAtri1', 'colAtri2', 'colAtri3', 'colAtri4',
    'colAtri5', 'colAtri6', 'colAtri7', 'colAtri8', 'colAtri9',
  ],
  /** Longitudes max. columnas string en [Empresas] (evitar SQLSTATE 22001). */
  'stringMaxLengths' => [
    'Codigo' => 3,
    'Nombre' => 50,
    'NombreFiscal' => 200,
    'CodigoExterno' => 10,
    'NIF' => 16,
    'Direccion' => 50,
    'CodigoPostal' => 8,
    'Poblacion' => 50,
    'Provincia' => 50,
    'Pais' => 30,
    'Telefono1' => 10,
    'Telefono2' => 10,
    'Fax' => 10,
    'Modem' => 10,
    'EMail' => 50,
    'PasaporteFitosanitario' => 20,
    'Divisa' => 2,
    'DivisaAlt' => 2,
    'CentroCoste' => 10,
    'UnidadComunicacion' => 2,
    'CodIvaSuperReducido' => 3,
    'CodIvaReducido' => 3,
    'CodIvaNormal' => 3,
    'CodIvaIncrementado' => 3,
    'CodIvaEsp5' => 3,
    'CodIvaEsp6' => 3,
    'SerieFacturas' => 3,
    'SerieAbonos' => 3,
    'RecalculoTarifas' => 2,
    'ArticuloMantenimiento' => 18,
    'PathExcelEstadisticas' => 100,
    'LiteralFactura' => 200,
    'LiteralFacturaContado' => 200,
    'LiteralPresupuesto' => 200,
    'LiteralVale' => 50,
    'Atri0' => 15,
    'Atri1' => 15,
    'Atri2' => 15,
    'Atri3' => 15,
    'Atri4' => 15,
    'Atri5' => 15,
    'Atri6' => 15,
    'Atri7' => 15,
    'Atri8' => 15,
    'Atri9' => 15,
  ],
  /**
   * Defaults de alta alineados con legacy (tienda 3 vs 4):
   * numericos a 0, textos vacios, RecalculoTarifas=MA.
   * Se aplican si el campo no viene o llega null.
   */
  'createDefaults' => [
    'Prefijo' => 0,
    'Vales_Em' => 0,
    'Vales_Re' => 0,
    'DecimalesPrecio' => 0,
    'Aecoc' => 0,
    'UltVale' => 0,
    'UltEnvioTransporte' => 0,
    'UltFicheroRecepcion' => 0,
    'UltFicheroRecepcionC' => 0,
    'CopiasAlbaranReparto' => 0,
    'CopiasAlbaran' => 0,
    'CopiasFactura' => 0,
    'CopiasFacturaReparto' => 0,
    'CopiasSimulacion' => 0,
    'ImpEtiquetasSinEans' => 0,
    'ImpEtiquetasSoloEansPropios' => 0,
    'MinimoFidelizacion' => 0,
    'MinimoCambioVales' => 0,
    'ImporteObligatorioFactura' => 0,
    'LiteralInvitacion' => 0,
    'RecalculoTarifas' => 'MA',
    'Fax' => '',
    'Modem' => '',
    'CodigoExterno' => '',
    'UnidadComunicacion' => '',
    'CentroCoste' => '',
    'ArticuloMantenimiento' => '',
    'ArticuloTransporte' => '',
    'ArticuloCubiertos' => '',
    'PathExcelEstadisticas' => '',
    'SerieFacturas' => '',
    'SerieAbonos' => '',
    'LiteralFactura' => '',
    'LiteralFacturaContado' => '',
    'LiteralPresupuesto' => '',
    'LiteralVale' => '',
    'Literal4' => '',
    'Literal5' => '',
    'Literal6' => '',
    'Literal7' => '',
    'Literal8' => '',
    'Literal9' => '',
    'Literal10' => '',
    'Literal11' => '',
    'Literal12' => '',
    'Literal13' => '',
    'Literal14' => '',
    'Literal15' => '',
    'Literal16' => '',
    'Literal17' => '',
    'Literal18' => '',
    'Literal19' => '',
    'Literal20' => '',
    'Literal21' => '',
    'Literal22' => '',
    'Literal23' => '',
    'Literal24' => '',
    'Literal25' => '',
    'Literal26' => '',
    'Literal27' => '',
    'Literal28' => '',
    'Literal29' => '',
    'Literal30' => '',
    'Atri0' => '',
    'Atri1' => '',
    'Atri2' => '',
    'Atri3' => '',
    'Atri4' => '',
    'Atri5' => '',
    'Atri6' => '',
    'Atri7' => '',
    'Atri8' => '',
    'Atri9' => '',
    'ColAtri0' => 0,
    'ColAtri1' => 0,
    'ColAtri2' => 0,
    'ColAtri3' => 0,
    'ColAtri4' => 0,
    'ColAtri5' => 0,
    'ColAtri6' => 0,
    'ColAtri7' => 0,
    'ColAtri8' => 0,
    'ColAtri9' => 0,
    'DesayunoHotelAdultos' => '',
    'DesayunoHotelNiños' => '',
    'AlmuerzoHotelAdultos' => '',
    'AlmuerzoHotelNiños' => '',
    'CenaHotelAdultos' => '',
    'CenaHotelNiños' => '',
    'HoraSalidaHotel' => '',
    'TicketSI_Certificado' => '',
    'TicketSI_CertificadoCP' => '',
    'Telefono1' => '',
    'Telefono2' => '',
    'NIF' => '',
    'Direccion' => '',
    'Poblacion' => '',
    'CodigoPostal' => '',
    'Provincia' => '',
    'Pais' => '',
    'EMail' => '',
    'NombreFiscal' => '',
    'PasaporteFitosanitario' => '',
    'CodIvaNormal' => '',
    'CodIvaReducido' => '',
    'CodIvaSuperReducido' => '',
    'CodIvaIncrementado' => '',
    'CodIvaEsp5' => '',
    'CodIvaEsp6' => '',
    'SumarDescuento' => 0,
  ],
];
