<?php

declare(strict_types=1);

/**
 * Mapeo API -> columnas [Empresas] para ficha completa de tienda.
 */
return [
  'fields' => [
    'codigo' => 'Codigo',
    'nombre' => 'Nombre',
    'nombreFiscal' => 'NombreFiscal',
    'codigoExterno' => 'CodigoExterno',
    'nif' => 'NIF',
    'direccion' => 'Direccion',
    'codigoPostal' => 'CodigoPostal',
    'poblacion' => 'Poblacion',
    'provincia' => 'Provincia',
    'pais' => 'Pais',
    'telefono1' => 'Telefono1',
    'telefono2' => 'Telefono2',
    'email' => 'EMail',
    'pasaporteFitosanitario' => 'PasaporteFitosanitario',
    'almacenCodigo' => 'Almacen',
    'literalFacturaDiferida' => 'LiteralFactura',
    'literalFacturaContado' => 'LiteralFacturaContado',
    'literalPresupuesto' => 'LiteralPresupuesto',
    'literalVale' => 'LiteralVale',
    'literalTicket' => 'LiteralTicket',
    'codIvaSuperReducido' => 'CodIvaSuperReducido',
    'codIvaReducido' => 'CodIvaReducido',
    'codIvaNormal' => 'CodIvaNormal',
    'codIvaIncrementado' => 'CodIvaIncrementado',
    'codIvaEsp5' => 'CodIvaEsp5',
    'codIvaEsp6' => 'CodIvaEsp6',
    'swIva' => 'SW_IVA',
    'recargo' => 'Recargo',
    'regimenCanario' => 'RegimenCanario',
    'intPreciosIvaIncluido' => 'IntPreciosIvaIncludo',
    'divisa' => 'Divisa',
    'divisaAlt' => 'DivisaAlt',
    'dto' => 'Dto',
    'sumarDescuento' => 'SumarDescuento',
    'bloqueoFidelizacion' => 'BloqueoFidelizacion',
    'pjeRetIrpf' => 'PjeRetIrpf',
    'ctbRetIrpf' => 'CtbRetIrpf',
    'centroCoste' => 'CentroCoste',
    'solicitarPerfil' => 'SolicitarPerfil',
    'tarifa' => 'Tarifa',
    'datos' => 'Datos',
    'prefijo' => 'Prefijo',
    'serieFacturas' => 'SerieFacturas',
    'facturasRectificativas' => 'FacturasRectificativas',
    'serieAbonos' => 'SerieAbonos',
    'minimoFidelizacion' => 'MinimoFidelizacion',
    'valesEmitidos' => 'Vales_Em',
    'valesRecibidos' => 'Vales_Re',
    'esCentral' => 'Central',
    'facturaLaCentral' => 'FacturaLaCentral',
    'comunicaCentral' => 'ComunicaCentral',
    'unidadComunicacion' => 'UnidadComunicacion',
    'almacenesInternos' => 'AlmacenesInternos',
    'conexionOnline' => 'ConexionOnline',
    'avisoStockCero' => 'AvisoStockCero',
    'dtoSiCambioPrecio' => 'DtoSiCambioPrecio',
    'desglosarBasesTicketIvaInc' => 'DesglosarBasesTicketIvaInc',
    'imprimirCodigoArticulo' => 'ImprimirCodigoArticulo',
    'obligarDineroEntregado' => 'ObligarDineroEntregado',
    'impSaldoTicket' => 'ImpSaldoTicket',
    'crearReciboCredito' => 'CrearReciboCredito',
    'aecoc' => 'Aecoc',
    'genBarras' => 'GenBarras',
    'genDesdeCodigo' => 'GenDesdeCodigo',
    'genClientes' => 'GenClientes',
    'genArticulos' => 'GenArticulos',
    'genProveedores' => 'GenProveedores',
    'articuloMantenimiento' => 'ArticuloMantenimiento',
    'controlVales' => 'ControlVales',
    'minimoCambioVales' => 'MinimoCambioVales',
    'importeObligatorioFactura' => 'ImporteObligatorioFactura',
    'tarifa1Escalado' => 'Tarifa1Escalado',
    'tarifa2Escalado' => 'Tarifa2Escalado',
    'tarifa3Escalado' => 'Tarifa3Escalado',
    'tarifa4Escalado' => 'Tarifa4Escalado',
    'tarifa5Escalado' => 'Tarifa5Escalado',
    'tarifa6Escalado' => 'Tarifa6Escalado',
    'tarifa7Escalado' => 'Tarifa7Escalado',
    'tarifa8Escalado' => 'Tarifa8Escalado',
    'tarifa9Escalado' => 'Tarifa9Escalado',
    'checkProveedor' => 'CheckProveedor',
    'cambiaProveedor' => 'CambiaProveedor',
    'maximizarListado' => 'MaximizarListado',
    'copiasAlbaranReparto' => 'CopiasAlbaranReparto',
    'copiasAlbaran' => 'CopiasAlbaran',
    'copiasFactura' => 'CopiasFactura',
    'copiasFacturaReparto' => 'CopiasFacturaReparto',
    'copiasSimulacion' => 'CopiasSimulacion',
    'impEtiquetasSinEans' => 'ImpEtiquetasSinEans',
    'etiquetasIvaIncluido' => 'EtiquetasIvaIncluido',
    'impEtiquetasSoloEansPropios' => 'ImpEtiquetasSoloEansPropios',
    'decimalesPrecio' => 'DecimalesPrecio',
    'solicitarPerfilParam' => 'SolicitarPerfil',
    'desglosarEscandallo' => 'DesglosarEscandallo',
    'recalculoTarifas' => 'RecalculoTarifas',
    'literalInvitacion' => 'LiteralInvitacion',
    'atri0' => 'Atri0',
    'atri1' => 'Atri1',
    'atri2' => 'Atri2',
    'atri3' => 'Atri3',
    'atri4' => 'Atri4',
    'atri5' => 'Atri5',
    'atri6' => 'Atri6',
    'atri7' => 'Atri7',
    'atri8' => 'Atri8',
    'atri9' => 'Atri9',
    'colAtri0' => 'ColAtri0',
    'colAtri1' => 'ColAtri1',
    'colAtri2' => 'ColAtri2',
    'colAtri3' => 'ColAtri3',
    'colAtri4' => 'ColAtri4',
    'colAtri5' => 'ColAtri5',
    'colAtri6' => 'ColAtri6',
    'colAtri7' => 'ColAtri7',
    'colAtri8' => 'ColAtri8',
    'colAtri9' => 'ColAtri9',
    'appWeb' => 'AppWeb',
    'litPiePedidoCompra' => 'LitPiePedidoCompra',
    'pathExcelEstadisticas' => 'PathExcelEstadisticas',
    'centrarLiteralesAdicionales' => 'CentrarlLiteralesAdicionales',
    'literal6' => 'Literal6',
    'literal7' => 'Literal7',
    'literal8' => 'Literal8',
    'literal9' => 'Literal9',
    'literal10' => 'Literal10',
    'literal11' => 'Literal11',
    'literal12' => 'Literal12',
    'literal13' => 'Literal13',
    'literal14' => 'Literal14',
    'literal15' => 'Literal15',
    'literal16' => 'Literal16',
    'literal17' => 'Literal17',
    'literal18' => 'Literal18',
    'literal19' => 'Literal19',
    'literal20' => 'Literal20',
    'literal21' => 'Literal21',
    'literal22' => 'Literal22',
    'literal23' => 'Literal23',
    'literal24' => 'Literal24',
    'literal25' => 'Literal25',
    'ultPedidoCom' => 'UltPedidoCom',
    'ultAlbaranCom' => 'UltAlbaranCom',
    'ultAlbaranVen' => 'UltAlbaranVen',
    'ultAlbaranTra' => 'UltAlbaranTra',
    'ultTicket' => 'UltTicket',
    'ultFactura' => 'UltFactura',
    'ultFacturaDiferida' => 'UltFacturaDiferida',
    'ultPedidoCli' => 'UltPedidoCli',
    'ultEnvio' => 'UltEnvio',
    'ultEan' => 'UltEan',
    'ultCliente' => 'UltCliente',
    'ultAbono' => 'UltAbono',
    'ultAbonoDiferido' => 'UltAbonoDiferido',
    'ultProveedor' => 'UltProveedor',
    'ultPreFactura' => 'UltPreFactura',
    'ultOrdenFabricacion' => 'UltOrdenFabricacion',
    'ultTransacCajon' => 'UltTransacCajon',
    'ultFicheroRecepcion' => 'UltFicheroRecepcion',
    'ultFicheroRecepcionC' => 'UltFicheroRecepcionC',
    'activo' => 'Baja',
  ],
  'booleanFields' => [
    'esCentral', 'facturaLaCentral', 'comunicaCentral', 'almacenesInternos', 'conexionOnline',
    'avisoStockCero', 'dtoSiCambioPrecio', 'desglosarBasesTicketIvaInc', 'imprimirCodigoArticulo',
    'obligarDineroEntregado', 'impSaldoTicket', 'crearReciboCredito', 'genBarras', 'genDesdeCodigo',
    'genClientes', 'genArticulos', 'genProveedores', 'controlVales', 'tarifa1Escalado', 'tarifa2Escalado',
    'tarifa3Escalado', 'tarifa4Escalado', 'tarifa5Escalado', 'tarifa6Escalado', 'tarifa7Escalado',
    'tarifa8Escalado', 'tarifa9Escalado', 'checkProveedor', 'cambiaProveedor', 'maximizarListado',
    'etiquetasIvaIncluido', 'desglosarEscandallo', 'appWeb', 'centrarLiteralesAdicionales',
    'swIva', 'recargo', 'regimenCanario', 'intPreciosIvaIncluido', 'sumarDescuento', 'bloqueoFidelizacion',
    'solicitarPerfil', 'facturasRectificativas', 'activo',
  ],
];
