import type { DocumentoPlantilla } from './types'

/** Esqueleto basado en albaranes/albaran.pdf */
export const plantillaAlbaran: DocumentoPlantilla = {
  id: 'albaran-std',
  tipo: 'albaran',
  nombre: 'Albarán estándar',
  descripcion: 'Plantilla base según albarán legacy (Garden Center Gaià)',
  version: 2,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 12, left: 10 },
  },
  blocks: [
    {
      id: 'emblema',
      type: 'emblema',
      x: 10,
      y: 10,
      w: 28,
      h: 28,
      label: 'Emblema',
      bind: ['empresa.emblemaUrl'],
      props: { fit: 'contain' },
    },
    {
      id: 'empresa',
      type: 'empresa-cabecera',
      x: 42,
      y: 10,
      w: 68,
      h: 32,
      bind: [
        'empresa.nombre',
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.fax',
        'empresa.email',
      ],
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 114,
      y: 12,
      w: 81,
      h: 14,
      label: 'ALBARAN',
      bind: ['documento.numero', 'documento.serie'],
    },
    {
      id: 'meta',
      type: 'bloque-meta',
      x: 114,
      y: 28,
      w: 81,
      h: 36,
      bind: [
        'documento.fecha',
        'documento.suPedido',
        'documento.albaran',
        'documento.terminalSesion',
        'documento.atendidoPor',
        'documento.fechaEntrega',
      ],
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 10,
      y: 46,
      w: 95,
      h: 42,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.pais',
        'cliente.cif',
        'cliente.telefono',
      ],
    },
    {
      id: 'transporte',
      type: 'campo',
      x: 110,
      y: 66,
      w: 85,
      h: 16,
      label: 'Transportista / Portes',
      bind: ['documento.transportista', 'documento.portes'],
    },
    {
      id: 'obs',
      type: 'campo',
      x: 10,
      y: 90,
      w: 185,
      h: 12,
      label: 'Observaciones',
      bind: ['documento.observaciones'],
    },
    {
      id: 'barcode',
      type: 'codigo-barras',
      x: 10,
      y: 104,
      w: 70,
      h: 14,
      bind: ['documento.codigoBarras'],
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 122,
      w: 190,
      h: 100,
      columns: [
        { key: 'articulo', label: 'Artículo', width: 28 },
        { key: 'descripcion', label: 'Descripción', width: 52 },
        { key: 'unidades', label: 'Unidades', width: 18 },
        { key: 'precioSinIva', label: 'Precio Sin Iva', width: 24 },
        { key: 'dto', label: 'Dto', width: 14 },
        { key: 'pjeIva', label: '%IVA', width: 14 },
        { key: 'importe', label: 'Importe', width: 22 },
        { key: 'pvp', label: 'P.V.P.', width: 18 },
      ],
      bind: ['lineas'],
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 110,
      y: 228,
      w: 90,
      h: 32,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE EU' },
    },
    {
      id: 'qr-verifactu',
      type: 'qr-verifactu',
      x: 10,
      y: 228,
      w: 32,
      h: 36,
      label: 'QR Verifactu',
      bind: ['verifactu.qrPayload', 'verifactu.url'],
      props: { quietZoneMm: 1, errorCorrection: 'M' },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 10,
      y: 275,
      w: 190,
      h: 10,
      bind: ['empresa.razonSocial', 'empresa.nif', 'documento.pagina'],
      props: { plantilla: '{{empresa.razonSocial}} N.I.F.{{empresa.nif}}  Página {{documento.pagina}}' },
    },
  ],
}
