import type { DocumentoPlantilla } from './types'

/** Esqueleto basado en albaranes/albaran.pdf (Garden Center Gaià). */
export const plantillaAlbaran: DocumentoPlantilla = {
  id: 'albaran-std',
  tipo: 'albaran',
  nombre: 'Albarán estándar',
  descripcion: 'Plantilla base según albarán legacy (Garden Center Gaià)',
  version: 4,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 12, left: 10 },
  },
  blocks: [
    {
      id: 'empresa',
      type: 'empresa-cabecera',
      x: 10,
      y: 10,
      w: 100,
      h: 28,
      bind: [
        'empresa.nombre',
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.fax',
        'empresa.email',
      ],
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 118,
      y: 12,
      w: 82,
      h: 12,
      label: 'ALBARAN',
      bind: [],
      props: { fontSizeMm: 5.2, fontWeight: 'bold' },
    },
    {
      id: 'sep-cabecera',
      type: 'separador',
      x: 10,
      y: 40,
      w: 190,
      h: 2,
    },
    {
      id: 'numero',
      type: 'campo',
      x: 12,
      y: 44,
      w: 90,
      h: 6,
      label: 'ALBARAN',
      bind: ['documento.numero'],
      props: { inline: true },
    },
    {
      id: 'meta',
      type: 'bloque-meta',
      x: 12,
      y: 51,
      w: 90,
      h: 36,
      bind: [
        'documento.fecha',
        'documento.suPedido',
        'documento.transportista',
        'documento.portes',
        'documento.atendidoPor',
        'documento.terminalSesion',
        'documento.albaran',
      ],
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 106,
      y: 44,
      w: 94,
      h: 38,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.pais',
        'cliente.telefono',
        'cliente.cif',
      ],
    },
    {
      id: 'barcode',
      type: 'codigo-barras',
      x: 140,
      y: 84,
      w: 60,
      h: 8,
      bind: ['documento.codigoBarras'],
    },
    {
      id: 'sep-observaciones',
      type: 'separador',
      x: 10,
      y: 94,
      w: 190,
      h: 2,
    },
    {
      id: 'obs',
      type: 'campo',
      x: 10,
      y: 96,
      w: 190,
      h: 9,
      label: 'Observaciones',
      bind: ['documento.observaciones'],
    },
    {
      id: 'fecha-entrega',
      type: 'campo',
      x: 10,
      y: 106,
      w: 90,
      h: 5,
      label: 'FECHA ENTREGA',
      bind: ['documento.fechaEntrega'],
      props: { inline: true, etiquetaPlana: true, fontSizeMm: 2.4, fontWeight: 'bold' },
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 112,
      w: 190,
      h: 132,
      columns: [
        { key: 'articulo', label: 'Artículo', width: 14 },
        { key: 'descripcion', label: 'Descripción', width: 32 },
        { key: 'unidades', label: 'Unidades', width: 10, align: 'right' },
        { key: 'precioSinIva', label: 'Precio Sin Iva', width: 12, align: 'right' },
        { key: 'dto', label: 'Dto', width: 7, align: 'right' },
        { key: 'pjeIva', label: '%IVA', width: 7, align: 'right' },
        { key: 'importe', label: 'Importe', width: 9, align: 'right' },
        { key: 'pvp', label: 'P.V.P.', width: 9, align: 'right' },
      ],
      bind: ['lineas'],
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 118,
      y: 248,
      w: 82,
      h: 28,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE EU' },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 10,
      y: 284,
      w: 190,
      h: 6,
      bind: ['empresa.razonSocial', 'empresa.nif', 'documento.pagina'],
      props: { plantilla: '{{empresa.razonSocial}} N.I.F.{{empresa.nif}}  Página {{documento.pagina}}' },
    },
  ],
}
