import type { DocumentoPlantilla } from './types'

/**
 * Réplica de la factura de contado legacy (formato de Can Juanito Vivers /
 * Garden Center Gaià): datos de empresa arriba a la izquierda (el logo solo
 * aparece si hay fichero en la carpeta `logos`), título FACTURA a la derecha,
 * caja de datos del documento junto a la del cliente, observaciones, tabla
 * de líneas agrupada por albarán y totales al pie.
 */
export const plantillaFacturaContado: DocumentoPlantilla = {
  id: 'factura-contado-std',
  tipo: 'factura-contado',
  nombre: 'Factura contado',
  descripcion: 'Plantilla base según factura de contado legacy',
  version: 5,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 12, left: 10 },
  },
  blocks: [
    {
      id: 'qr-tributario',
      type: 'qr-verifactu',
      x: 10,
      y: 10,
      w: 28,
      h: 28,
      label: 'QR tributario',
      bind: ['verifactu.qrPayload', 'verifactu.url'],
      props: { quietZoneMm: 1, errorCorrection: 'M', rotulo: 'VERI*FACTU' },
    },
    {
      id: 'empresa',
      type: 'empresa-cabecera',
      x: 40,
      y: 10,
      w: 76,
      h: 28,
      bind: [
        'empresa.nombre',
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.fax',
        'empresa.email',
      ],
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 118,
      y: 14,
      w: 82,
      h: 11,
      label: 'FACTURA',
      bind: [],
      props: { fontSizeMm: 5.2, fontWeight: 'bold' },
    },
    {
      id: 'sep-cabecera',
      type: 'separador',
      x: 10,
      y: 40,
      w: 190,
      h: 2,
    },
    {
      id: 'numero',
      type: 'campo',
      x: 12,
      y: 44,
      w: 90,
      h: 6,
      label: 'FACTURA',
      bind: ['documento.numero'],
      props: { inline: true },
    },
    {
      id: 'meta',
      type: 'bloque-meta',
      x: 12,
      y: 51,
      w: 90,
      h: 34,
      bind: [
        'documento.albaran',
        'documento.fecha',
        'documento.suPedido',
        'documento.transportista',
        'documento.portes',
        'documento.atendidoPor',
        'documento.terminalSesion',
      ],
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 106,
      y: 44,
      w: 94,
      h: 36,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.pais',
        'cliente.telefono',
        'cliente.cif',
      ],
    },
    {
      id: 'barcode',
      type: 'codigo-barras',
      x: 140,
      y: 82,
      w: 60,
      h: 8,
      bind: ['documento.codigoBarras'],
    },
    {
      id: 'sep-observaciones',
      type: 'separador',
      x: 10,
      y: 92,
      w: 190,
      h: 2,
    },
    {
      id: 'obs',
      type: 'campo',
      x: 10,
      y: 94,
      w: 190,
      h: 9,
      label: 'Observaciones',
      bind: ['documento.observaciones'],
    },
    {
      id: 'fecha-entrega',
      type: 'campo',
      x: 10,
      y: 104,
      w: 90,
      h: 5,
      label: 'FECHA ENTREGA',
      bind: ['documento.fechaEntrega'],
      props: { inline: true, etiquetaPlana: true, fontSizeMm: 2.4, fontWeight: 'bold' },
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 110,
      w: 190,
      h: 134,
      props: { agruparPorAlbaran: true, mostrarCabeceraAlbaran: true },
      columns: [
        { key: 'articulo', label: 'Artículo', width: 12 },
        { key: 'descripcion', label: 'Descripción', width: 30 },
        { key: 'unidades', label: 'Unidades', width: 10, align: 'right' },
        { key: 'precioSinIva', label: 'Precio Sin Iva', width: 13, align: 'right' },
        { key: 'dto', label: 'Dto', width: 7, align: 'right' },
        { key: 'pjeIva', label: '%IVA', width: 7, align: 'right' },
        { key: 'importe', label: 'Importe', width: 11, align: 'right' },
        { key: 'pvp', label: 'P.V.P.', width: 10, align: 'right' },
      ],
      bind: ['lineas'],
    },
    {
      id: 'literal-tienda',
      type: 'campo',
      x: 10,
      y: 246,
      w: 100,
      h: 10,
      bind: ['tienda.literalFacturaContado'],
      props: { fontSizeMm: 2.2 },
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 118,
      y: 248,
      w: 82,
      h: 28,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE EU' },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 10,
      y: 284,
      w: 190,
      h: 6,
      bind: ['empresa.razonSocial', 'empresa.nif', 'documento.pagina'],
      props: { plantilla: '{{empresa.razonSocial}} N.I.F.{{empresa.nif}}  Página {{documento.pagina}}' },
    },
  ],
}
