import type { DocumentoPlantilla } from './types'

const VERDE_LEGACY = '#7f918c'
const VERDE_SUAVE = '#edf1ef'

/**
 * Factura de crédito / diferida basada en `Detalles/FRA PROVES.pdf`
 * (Crystal Reports "Factura Estandard", 34 facturas de septiembre de 2026).
 *
 * Rasgos principales: membrete en la esquina superior derecha, título y datos
 * de factura/cliente en dos columnas, forma de pago, líneas agrupadas por
 * albarán, vencimientos a la izquierda y totales al pie derecho.
 */
export const plantillaFacturaCredito: DocumentoPlantilla = {
  id: 'factura-credito-std',
  tipo: 'factura-credito',
  nombre: 'Factura crédito / diferida',
  descripcion: 'Plantilla Logicart según FRA PROVES.pdf (factura diferida legacy)',
  version: 3,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 10, left: 10 },
  },
  blocks: [
    {
      id: 'empresa-direccion',
      type: 'campo',
      x: 106,
      y: 14,
      w: 38,
      h: 25,
      bind: [
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.email',
      ],
      props: { align: 'right', fontSizeMm: 1.75 },
    },
    {
      id: 'emblema',
      type: 'emblema',
      x: 146,
      y: 14,
      w: 50,
      h: 20,
      label: 'Emblema',
      bind: ['empresa.emblemaUrl'],
      props: { fit: 'contain' },
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 10,
      y: 51,
      w: 75,
      h: 10,
      label: 'FACTURA',
      bind: [],
      props: {
        fontSizeMm: 5.2,
        fontWeight: 'bold',
        accentColor: VERDE_LEGACY,
      },
    },
    {
      id: 'numero',
      type: 'campo',
      x: 10,
      y: 63,
      w: 72,
      h: 6,
      label: 'FACTURA',
      bind: ['documento.numero'],
      props: {
        inline: true,
        accentColor: VERDE_LEGACY,
        accentSoftColor: VERDE_LEGACY,
        accentTextColor: '#ffffff',
      },
    },
    {
      id: 'fecha',
      type: 'campo',
      x: 35,
      y: 69,
      w: 47,
      h: 5,
      label: 'Fecha',
      bind: ['documento.fecha'],
      props: { inline: true, etiquetaPlana: true, fontWeight: 'bold' },
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 84,
      y: 63,
      w: 112,
      h: 38,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.telefono',
        'cliente.cif',
      ],
      props: {
        accentColor: VERDE_LEGACY,
        accentSoftColor: VERDE_LEGACY,
        accentTextColor: '#ffffff',
      },
    },
    {
      id: 'cuenta-cliente',
      type: 'campo',
      x: 120,
      y: 99,
      w: 76,
      h: 5,
      bind: ['cliente.cuentaBancaria'],
      props: { fontSizeMm: 2 },
    },
    {
      id: 'forma-pago-cabecera',
      type: 'campo',
      x: 10,
      y: 79,
      w: 72,
      h: 6,
      bind: ['documento.formaPago'],
      props: { fontSizeMm: 2.25, fontWeight: 'bold' },
    },
    {
      id: 'observaciones',
      type: 'campo',
      x: 10,
      y: 88,
      w: 58,
      h: 8,
      label: 'Observaciones',
      bind: ['documento.observaciones'],
      props: {
        accentColor: VERDE_LEGACY,
        accentSoftColor: VERDE_LEGACY,
        accentTextColor: '#ffffff',
      },
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 106,
      w: 190,
      h: 116,
      props: {
        agruparPorAlbaran: true,
        mostrarCabeceraAlbaran: true,
        permitirNotasLinea: true,
        accentColor: VERDE_LEGACY,
        accentSoftColor: VERDE_SUAVE,
        accentTextColor: '#ffffff',
      },
      columns: [
        { key: 'articulo', label: 'Artículo', width: 14 },
        { key: 'descripcion', label: 'Descripción', width: 39 },
        { key: 'unidades', label: 'Unidades', width: 10, align: 'right' },
        { key: 'precio', label: 'Precio', width: 10, align: 'right' },
        { key: 'dto', label: 'Dto', width: 7, align: 'right' },
        { key: 'pjeIva', label: '%IVA', width: 7, align: 'right' },
        { key: 'importe', label: 'Importe', width: 13, align: 'right' },
      ],
      bind: ['lineas'],
    },
    {
      id: 'nota-iva',
      type: 'texto',
      x: 10,
      y: 224,
      w: 105,
      h: 6,
      label: 'NOTA : El Precio no lleva el I.V.A. Incorporado',
      props: { fontSizeMm: 2.25, fontWeight: 'bold' },
    },
    {
      id: 'forma-pago-vencimientos',
      type: 'campo',
      x: 10,
      y: 233,
      w: 62,
      h: 5,
      bind: ['documento.formaPago'],
      props: { fontSizeMm: 2.15, fontWeight: 'bold' },
    },
    {
      id: 'vencimientos',
      type: 'vencimientos',
      x: 10,
      y: 239,
      w: 51,
      h: 27,
      bind: ['vencimientos'],
      props: {
        columnas: ['fecha', 'importe'],
        accentColor: VERDE_LEGACY,
        accentTextColor: '#ffffff',
      },
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 128,
      y: 252,
      w: 72,
      h: 31,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE FACTURA Eu' },
    },
    {
      id: 'legal',
      type: 'texto',
      x: 6,
      y: 284,
      w: 178,
      h: 5,
      label:
        'Logicart,S.L. NIF : B-58292129. Inscrita en el Registro Mercantil de Barcelona, Folio 38, Tomo 8.483, Libro 7.733, Sección 2ª, Hoja 98.801',
      props: {
        fontSizeMm: 1.55,
        rotateDeg: -90,
        transformOrigin: 'top left',
      },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 170,
      y: 286,
      w: 30,
      h: 5,
      bind: ['documento.pagina'],
      props: { plantilla: 'Página {{documento.pagina}}' },
    },
  ],
}

/** Misma composición que crédito, con el título propio de la rectificativa. */
export const plantillaFacturaRectificativa: DocumentoPlantilla = {
  ...plantillaFacturaCredito,
  id: 'factura-rectificativa-std',
  tipo: 'factura-rectificativa',
  nombre: 'Factura rectificativa',
  descripcion: 'Rectificativa con la composición Logicart de factura diferida',
  blocks: plantillaFacturaCredito.blocks.map((b) =>
    b.id === 'titulo' ? { ...b, label: 'FACTURA RECTIFICATIVA' } : b
  ),
}
