import type { DocumentoPlantilla } from './types'

/**
 * Esqueleto basado en albaranes/DiferidaYrectificatva.pdf (facturas crédito).
 * La rectificativa reutiliza la misma estructura con titulo distinto e importes negativos.
 */
export const plantillaFacturaCredito: DocumentoPlantilla = {
  id: 'factura-credito-std',
  tipo: 'factura-credito',
  nombre: 'Factura crédito / diferida',
  descripcion: 'Plantilla base según factura crédito legacy (IBAN, vencimientos, agrupación por albarán)',
  version: 2,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 12, left: 10 },
  },
  blocks: [
    {
      id: 'emblema',
      type: 'emblema',
      x: 10,
      y: 10,
      w: 28,
      h: 28,
      label: 'Emblema',
      bind: ['empresa.emblemaUrl'],
      props: { fit: 'contain' },
    },
    {
      id: 'empresa',
      type: 'empresa-cabecera',
      x: 42,
      y: 10,
      w: 70,
      h: 30,
      bind: [
        'empresa.nombre',
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.fax',
        'empresa.email',
      ],
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 118,
      y: 12,
      w: 77,
      h: 14,
      label: 'FACTURA',
      bind: ['documento.numero', 'documento.serie'],
      props: { etiquetaModo: 'CREDITO' },
    },
    {
      id: 'meta',
      type: 'bloque-meta',
      x: 118,
      y: 28,
      w: 77,
      h: 28,
      bind: ['documento.fecha', 'documento.observaciones'],
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 10,
      y: 44,
      w: 100,
      h: 40,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.pais',
        'cliente.cif',
        'cliente.telefono',
      ],
    },
    {
      id: 'banco',
      type: 'datos-bancarios',
      x: 10,
      y: 88,
      w: 185,
      h: 16,
      bind: ['empresa.banco', 'empresa.iban', 'empresa.swift'],
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 110,
      w: 190,
      h: 92,
      props: { agruparPorAlbaran: true, mostrarCabeceraAlbaran: true, permitirNotasLinea: true },
      columns: [
        { key: 'articulo', label: 'Artículo', width: 32 },
        { key: 'descripcion', label: 'Descripción', width: 70 },
        { key: 'unidades', label: 'Unidades', width: 20 },
        { key: 'precio', label: 'Precio', width: 24 },
        { key: 'dto', label: 'Dto', width: 14 },
        { key: 'importe', label: 'Importe', width: 22 },
        { key: 'pjeIva', label: '%IVA', width: 14 },
      ],
      bind: ['lineas'],
    },
    {
      id: 'qr-verifactu',
      type: 'qr-verifactu',
      x: 10,
      y: 210,
      w: 34,
      h: 38,
      label: 'QR Verifactu',
      bind: ['verifactu.qrPayload', 'verifactu.url'],
      props: { quietZoneMm: 1, errorCorrection: 'M' },
    },
    {
      id: 'vencimientos',
      type: 'vencimientos',
      x: 50,
      y: 210,
      w: 55,
      h: 28,
      bind: ['vencimientos'],
      props: { columnas: ['fecha', 'importe'] },
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 110,
      y: 210,
      w: 90,
      h: 36,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE FACTURA EU' },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 10,
      y: 275,
      w: 190,
      h: 10,
      bind: ['empresa.razonSocial', 'empresa.nif', 'documento.pagina'],
      props: { plantilla: '{{empresa.razonSocial}} N.I.F.{{empresa.nif}}  Página {{documento.pagina}}' },
    },
  ],
}

/** Misma estructura que crédito; titulo FACTURA RECTIFICATIVA. */
export const plantillaFacturaRectificativa: DocumentoPlantilla = {
  ...plantillaFacturaCredito,
  id: 'factura-rectificativa-std',
  tipo: 'factura-rectificativa',
  nombre: 'Factura rectificativa',
  descripcion: 'Basada en crédito; importes negativos / abonos',
  blocks: plantillaFacturaCredito.blocks.map((b) =>
    b.id === 'titulo' ? { ...b, label: 'FACTURA RECTIFICATIVA' } : b
  ),
}
