import type { DocumentoPlantilla } from './types'

/**
 * Réplica de la factura de contado legacy (formato de Can Juanito Vivers):
 * QR tributario y datos de empresa arriba a la izquierda, título FACTURA a la
 * derecha, caja de datos del documento junto a la del cliente, observaciones,
 * tabla de líneas agrupada por albarán, literal de tienda y totales al pie.
 *
 * Los primeros 30 mm quedan libres para el membrete preimpreso del papel; en
 * papel blanco hay que añadir en el diseñador un bloque `emblema` y/o texto.
 */
export const plantillaFacturaContado: DocumentoPlantilla = {
  id: 'factura-contado-std',
  tipo: 'factura-contado',
  nombre: 'Factura contado',
  descripcion: 'Plantilla base según factura de contado legacy',
  version: 3,
  page: {
    format: 'A4',
    orientation: 'portrait',
    marginMm: { top: 10, right: 10, bottom: 12, left: 10 },
  },
  blocks: [
    {
      id: 'qr-titulo',
      type: 'texto',
      x: 10,
      y: 31,
      w: 45,
      h: 5,
      label: 'QR Tributario :',
      props: { fontSizeMm: 2.1 },
    },
    {
      id: 'qr-verifactu',
      type: 'qr-verifactu',
      x: 10,
      y: 36,
      w: 24,
      h: 30,
      label: 'QR Verifactu',
      bind: ['verifactu.qrPayload', 'verifactu.url'],
      props: { quietZoneMm: 1, errorCorrection: 'M' },
    },
    {
      id: 'sep-cabecera',
      type: 'separador',
      x: 10,
      y: 67,
      w: 190,
      h: 2,
    },
    {
      id: 'empresa',
      type: 'empresa-cabecera',
      x: 10,
      y: 69,
      w: 95,
      h: 22,
      bind: [
        'empresa.nombre',
        'empresa.direccion',
        'empresa.cp',
        'empresa.poblacion',
        'empresa.provincia',
        'empresa.telefono',
        'empresa.fax',
        'empresa.email',
      ],
    },
    {
      id: 'titulo',
      type: 'titulo-documento',
      x: 118,
      y: 76,
      w: 70,
      h: 11,
      label: 'FACTURA',
      bind: [],
      props: { fontSizeMm: 5.2, fontWeight: 'bold' },
    },
    {
      id: 'numero',
      type: 'campo',
      x: 12,
      y: 92,
      w: 90,
      h: 6,
      label: 'FACTURA',
      bind: ['documento.numero'],
      props: { inline: true },
    },
    {
      id: 'meta',
      type: 'bloque-meta',
      x: 12,
      y: 99,
      w: 90,
      h: 34,
      bind: [
        'documento.albaran',
        'documento.fecha',
        'documento.suPedido',
        'documento.transportista',
        'documento.portes',
        'documento.atendidoPor',
        'documento.terminalSesion',
      ],
    },
    {
      id: 'cliente',
      type: 'bloque-cliente',
      x: 106,
      y: 92,
      w: 94,
      h: 32,
      bind: [
        'cliente.codigo',
        'cliente.nombre',
        'cliente.direccion',
        'cliente.cp',
        'cliente.poblacion',
        'cliente.provincia',
        'cliente.pais',
        'cliente.telefono',
        'cliente.cif',
      ],
    },
    {
      id: 'barcode',
      type: 'codigo-barras',
      x: 140,
      y: 125,
      w: 60,
      h: 8,
      bind: ['documento.codigoBarras'],
    },
    {
      id: 'sep-observaciones',
      type: 'separador',
      x: 10,
      y: 134,
      w: 190,
      h: 2,
    },
    {
      id: 'obs',
      type: 'campo',
      x: 10,
      y: 136,
      w: 190,
      h: 9,
      label: 'Observaciones',
      bind: ['documento.observaciones'],
    },
    {
      id: 'fecha-entrega',
      type: 'campo',
      x: 10,
      y: 146,
      w: 90,
      h: 5,
      label: 'FECHA ENTREGA',
      bind: ['documento.fechaEntrega'],
      props: { inline: true, etiquetaPlana: true, fontSizeMm: 2.4, fontWeight: 'bold' },
    },
    {
      id: 'lineas',
      type: 'tabla-lineas',
      x: 10,
      y: 152,
      w: 190,
      h: 98,
      props: { agruparPorAlbaran: true, mostrarCabeceraAlbaran: true },
      columns: [
        { key: 'articulo', label: 'Articulo', width: 10 },
        { key: 'descripcion', label: 'Descripcion', width: 36 },
        { key: 'unidades', label: 'Unidades', width: 10, align: 'right' },
        { key: 'pvp', label: 'P.V.P.', width: 10, align: 'right' },
        { key: 'precioSinIva', label: 'Precio Sin Iva', width: 13, align: 'right' },
        { key: 'dto', label: 'Dto', width: 7, align: 'right' },
        { key: 'pjeIva', label: '%IVA', width: 7, align: 'right' },
        { key: 'importe', label: 'Importe', width: 7, align: 'right' },
      ],
      bind: ['lineas'],
    },
    {
      id: 'literal-tienda',
      type: 'campo',
      x: 10,
      y: 251,
      w: 100,
      h: 10,
      bind: ['tienda.literalFacturaContado'],
      props: { fontSizeMm: 2.2 },
    },
    {
      id: 'totales',
      type: 'totales-iva',
      x: 118,
      y: 255,
      w: 82,
      h: 26,
      bind: ['totales.base', 'totales.ivas', 'totales.importe'],
      props: { etiquetaTotal: 'IMPORTE EU' },
    },
    {
      id: 'pie',
      type: 'pie',
      x: 10,
      y: 284,
      w: 110,
      h: 6,
      bind: ['empresa.razonSocial', 'empresa.nif', 'documento.pagina'],
      props: { plantilla: '{{empresa.razonSocial}} N.I.F.{{empresa.nif}}  Página {{documento.pagina}}' },
    },
  ],
}
